### ISSUE TITLE
Color of saved games occasionally changes

### ISSUE THREAD

**Issue by phkb** [OoliteProject/oolite#123]
Win8 64bit. When more than one page of saved games is present, going from page 1 to page 2 will occasionally color on the the game files in orange, rather than yellow. 
![oolitesavescreen1](https://cloud.githubusercontent.com/assets/10691987/5890416/90cabc82-a4ad-11e4-89ec-a57a6d7a7683.png)
![oolitesavescreen2](https://cloud.githubusercontent.com/assets/10691987/5890417/9521b5f6-a4ad-11e4-88a2-87baaa41e1a1.png)

**Comment by AnotherCommander** [comment]
I reproduce this bug as follows:
1. Load up Oolite, go to Load Commander in the menu
![issue123_1](https://cloud.githubusercontent.com/assets/623526/5892475/feb0fcea-a4bf-11e4-874b-61f945212694.jpg)
2. Select the oolite.app folder one step up by doing Ctrl+Enter
![issue123_2](https://cloud.githubusercontent.com/assets/623526/5892478/17c8d2f2-a4c0-11e4-807b-9796dea498d3.jpg)
3. Re-enter ito oolite-saves folder with Ctrl+Enter
![issue123_3](https://cloud.githubusercontent.com/assets/623526/5892481/50a3d4f0-a4c0-11e4-886d-fd50bf395fc6.jpg)
