### ISSUE TITLE
Unable to Pause game on mission screen when allowInterrupt = false

### ISSUE THREAD

**Issue by phkb** [OoliteProject/oolite#125]
If a mission screen is opened through the interfaces (F4) page, and the "allowInterrupt" option is set to false in the runScreen options, pressing "P" to pause the game doesn't work. Tested in 1.81 and 1.80.

**Comment by cim--** [comment]
This is also the case if `allowInterrupt` is true, isn't it?

On a text entry mission screen, of course, the pause key certainly won't work, or you wouldn't be able to type whatever it was bound to. I'm not sure, given that, it's worth the effort to make it work on the select option mission screens.

**Comment by phkb** [comment]
Yeah, I see the point. Probably not worth it.
