### ISSUE TITLE
Oolite 1.80 / 1.82 mac os x strange behaviour

### ISSUE THREAD

**Issue by gmezzanotti** [OoliteProject/oolite#128]
I'm new on oolite world and this is the first version i try so i can't comment older versions.

Oolite run fine just on very first time, the following runs it's open the loading window and continue on it forever, the program doesn't freeze because i got response on menus.

If i try to run oolite as another user i get the same behavior.

If i try to run oolite developer i get the same behavior.

I just upgraded mac os x from 10.10.2 to 10.10.3, tried to run oolite again, first time ok and then same behavior.

Anyone could help me?

Thanks,
Marcello

**Comment by AnotherCommander** [comment]
We have a very similar report on the forum for version 1.82, running on OSX 10.10.4 (Yosemite). I am pasting in the details from the report for reference and updating the title to include  v1.82:

Quoting user JezA:
Begin quote
----------------------------------------------
I have recently downloaded Oolite v1.82 (for mac). On running the game for the first time, all works as expected. However, on exiting the game and trying to run it again, the loading screen appears but nothing further happens..

I have to delete the entire game directory, the Preferences plist, Cache and Log files, restart my mac book, unzip the game directory again and then the game will restart.

Has anyone experienced this problem, and does anyone have any thoughts as to why this might be happening?.

The Oolite Latest log file contains the following :

```
Opening log for Oolite version 1.82 (x86-64) under Mac OS X Version 10.10.4 (Build 14E46) at 2015-07-22 05:40:49 +0000.
Machine type: MacBookPro11,3, 16384 MiB memory, 4 (8 logical) x x86 (Haswell) @ 2300 MHz.
Build options: OpenAL, new planets.

Note that the contents of the log file can be adjusted by editing logcontrol.plist.

15:40:49.798 [dataCache.notFound]: No data cache found, starting from scratch.
15:40:50.529 [system]: -[SUHost sharedFrameworksPath]: unrecognized selector sent to instance 0x6000000013f0
```
The System log files contains:
```
Jul 22 16:27:16 {computername}.local Oolite[1337]: -[SUHost sharedFrameworksPath]: unrecognized selector sent to instance 0x608000001740
Jul 22 16:27:16 {computername} com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Oolite.1337): Failed to bootstrap path: path = /Users/{username}/Downloads/Oolite 1.82/Oolite.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle, error = 20: Not a directory
```
End quote
----------------------------------------------

**Comment by KonstantinosSykas** [comment]
From a quick lookup I did on the web, it seems that this behavior is coming up following an OS X upgrade. It seems that both our cases appeared just after an OS X upgrade, that would lead to a systemic root-cause. I will continue digging; I haven't found any feasible suggestion, apart from re-applying the upgrade, which I don't like.

**Comment by MaddTheSane** [comment]
What version of Sparkle is being used? This may be related to sparkle-project/Sparkle#571
