### ISSUE TITLE
Bug in "oolite-populator" "this._tradeStation" functon

### ISSUE THREAD

**Issue by phkb** [OoliteProject/oolite#131]
In the "this._tradeStation" function, there is a variable "tries" which is checked in a Do..While loop to limit the number of iterations of the loop. But the tries variable is never updated, and so will always equal zero.

**Comment by cim--** [comment]
I believe this is already fixed in the current build in commit c171f6850.

**Comment by phkb** [comment]
That'll teach me to look first before reporting! Sorry for distraction.
