### ISSUE TITLE
Deployment Build on Windows CPU Usage

### ISSUE THREAD

**Issue by AnotherCommander** [OoliteProject/oolite#133]
It looks like the Test Release Executable is of much better quality compared to the Deployment one, at least under Windows. The graphs of CPU usage speak for themselves. They show total CPU usage, but I can report that Task Manager shows that the Deployment executable alone uses about 60-70% CPU, while the Test Release one around 40-45%. Plus, I have not seen yet the TR executable reporducing the crash reported on issue 132, although more testing is needed..

Is this reproducible on the other ports?
![rundeplo](https://cloud.githubusercontent.com/assets/623526/7338279/57002424-ec47-11e4-9752-12291e18fcdd.jpg)
![runtest](https://cloud.githubusercontent.com/assets/623526/7338281/62328076-ec47-11e4-8600-9c42c3c1df18.jpg)

**Comment by cim--** [comment]
Not duplicated here on Linux:
test -> 30-50% usage
deploy -> 25-35% usage

Higher CPU usage in the deployment build isn't necessarily a problem, though, depending on where the bottlenecks in the system are. It might mean it's spending less time doing non-CPU stuff like file access or GPU adjusting, so can make more efficient use of the CPU.

How do the framerates compare between the two versions?

**Comment by AnotherCommander** [comment]
Framerates are exactly the same between the two.,

Who would ever think possible? That self-destruct option Threading Optimization that NVidia has was responsible for this one too! After disabling, both Deployment and Test use around 40% for me here.

I am closing this. Way to go NVidia...
