### ISSUE TITLE
BB change page problem

### ISSUE THREAD

**Issue by Egor17** [OoliteProject/oolite#135]
This keeps happening today  7/5/15;
	
General Error
SQL ERROR [ mysql4 ]

Too many connections [1040]

An sql error occurred while fetching this page. Please contact an administrator if this problem persists.
Never seen this before so have no idea if it's a BB problem or my Int. Provider or net os

**Comment by kanthoney** [comment]
It's a temporary problem with the bulletin board, and not anything to do with Oolite itself.
