### ISSUE TITLE
Cargo dumping bug

### ISSUE THREAD

**Issue by Glitch-kun** [OoliteProject/oolite#138]
If you dump all cargo, then die and automatically restart from your last save, you won't be able to dump cargo upon re-embarking.

Save download: https://mega.co.nz/#!W0NSDCoK!5MUQRTK3h3bLqLyzN_tmweyGvTK7SOYV_qtOFKPMp4M

To reproduce:
1. Embark
2. Dump all cargo
3. Suicide (etc. crashing into station)
4. Embark

**Comment by cim--** [comment]
Thanks for the report - fixed for next version now.
