### ISSUE TITLE
Disappearing parcels - possiblebug, non-repeatable (yet).

### ISSUE THREAD

**Issue by szopeno** [OoliteProject/oolite#142]
After fulfilling several parcels, I was frustrated to find out that still "none has ever heard abotu you delivering a parcel". Finally, i checked the savegames and find out that the number of parcels_fulfilled is 0; I manually edited it to 4, loaded, the status changed to "you are in the feeble beginnings of the parcel business", then I saved and the number of parcels_fulfilled fell down to 3; 

Unfortunately, the bug is not repeatable. After editing to "4" once again, it persisted despite several cycles of load/save. Then, suddenly, once again after fulfilling few parcel contracts, the number in parcel_fulfilled persisted at "16" and when manually modified to "17", it fell down to "16" again after save game. Since that time (two days of game play) the number seems to increase properly.

GNU/Linux, oolite 1.80, with oolite.oxp.Commander_McLane.Display_reputation.oxz

**Comment by cim--** [comment]
When you were originally delivering parcels, how long was it between each delivery? Parcel reputation does decay over time, so you might not have been delivering them quickly enough to get a permanent rep increase (or just got unlucky with the decay as its random when it happens)
 
When you edited your save game, did you also edit the `parcels_expired` and `parcels_unknown` keys to keep the total of all three at 70? If not, then they would have been adjusted back to a total of 70 which may have come from `parcels_fulfilled`

**Comment by AnotherCommander** [comment]
This one doesn't seem to be an actual game issue and the original reporter has not responded for nearly two years now. Additionally, he mentions that the issue could not be reproduced and we have not seen any similar reports related to contracts. Issue is closed.
