### ISSUE TITLE
Galactic Chart - Double-click moves "select" cursor away from planet

### ISSUE THREAD

**Issue by KonstantinosSykas** [OoliteProject/oolite#145]
Oolite arch: 64bit
Version-Revision: 1.82-6b2b640 
Add-ons: No
O/S: Win7 64bit

Description: "Select" cursor (the red one) is placed in the middle of nowhere.

Steps to reproduce:
1. Start Oolite, start new commander, normal start.
2. Press F6.
3. Double-click in empty space; "Data on <planet>" screen comes up.
4. Press F6. "Select" cursor (the red one) is placed in the middle of nowhere.

Screenshot:
![Red Cursor Position](http://i1124.photobucket.com/albums/l573/ksykas/Oolite%20Bugs/Oolite-Chart-RedCursorPosition.png)

**Comment by kanthoney** [comment]
Can you check branch `issue_145` for me?  I think i've fixed it but need to get back to work and don't want to commit to master in a hurry.

**Comment by kanthoney** [comment]
This also fixes a problem where if you're in the long range chart and double click, when you return it brings you back to the short range chart.

**Comment by AnotherCommander** [comment]
Tested and it works. Good to bring into master.
