### ISSUE TITLE
Viper exhausts render issue

### ISSUE THREAD

**Issue by AnotherCommander** [OoliteProject/oolite#150]
While testing Norby's fix for the Viper materials, I noticed a little render problem. I tested also with a Cobra MKI and the problem did not occur, so I  guess it's something local. It is minor, but it's there.
See the two pics below. There is extremely small difference in distance between the two. However, the exhaust plumes appear much shorter on the first one. The jump to the length you see on the second pic occurs from one frame to the next. It looks like there are specific angles from which this happens, or at least, is more evident.
![exhaustbug01](https://cloud.githubusercontent.com/assets/623526/7783738/c6ef6bae-014c-11e5-970e-485b16c48050.jpg)
![exhaustbug02](https://cloud.githubusercontent.com/assets/623526/7783739/cd08fe10-014c-11e5-8ebc-837f10f64a48.jpg)
If you approach very slowly while this happens, you can see the plumes getting progressively shorter and look "cut" and at a certain distance they jump back to their normal length and appear as in the second pic.

**Comment by AnotherCommander** [comment]
Two more observations: 1.80 does not seem to have this issue and it looks like the distance where the change happens is exactly 0.180km (using the standard CobraIII as player ship).

**Comment by kanthoney** [comment]
I believe it entered master with the two pass rendering merge - the bug shows in 1a45adbb55304e3f6a638168527550e469f755a5 but not in 7f90b5dcd64575da92bf6da3c84b81baf099eeac.

**Comment by kanthoney** [comment]
Bug introduced with 03e4cce3463198604026996ae7ea496f247054d6 - I guess when the plume crosses the two pass boundary at 100m, the part on this side of the boundary is truncated until you get close enough for the whole plume to be inside the boundary, at which point it springs back into view.

**Comment by kanthoney** [comment]
I've tried three fixes, none of which have worked.  Firstly I tried a quite involved fix of keeping track of the plume length in the `update` function.  Then I tried a quick and dirty fix - changing

````
- (double)findCollisionRadius
{
return 0; // FIXME: something sensible. Where does plume length come from anyway?
}
````

to a constant value - and that doesn't work either, even if you change it to something OTT like 400.  Neither did setting `collision_radius` to something non-zero in `init`.

**Comment by AnotherCommander** [comment]
The issue happens also with other entities, like flashers. I have the Docking Lights OXP installed and that puts a line of flashers from nav buoy to station door. Just launching and approaching these flashers demonstrates the bug. The flashers disappear much earlier than they should as they get approached.

Putting the INTERMEDIATE_CLEAR_DEPTH back to 50000 in MyOpenGLView.h fixes the problem, but I very much doubt that it is the solution we are looking for and am not sure what side effects any arbitrary value might have.

**Comment by cim--** [comment]
50000 - which is the sort of value I originally wanted for it - caused very weird effects as you approach the planet surface. They might have been fixed now - I'll check.

The problem is that the `ShipEntity::frustumRadius` method returns `_profileRadius`, which doesn't include the exhaust plumes or flashers in it. The flashers because `addSubentityToCollisionRadius` isn't called for them (and shouldn't be - they only need the `_profileRadius` update) - the exhaust plumes not at all.

@kanthoney - if you try the complicated fix you had before, but apply it back to the _profileRadius of the main entity, it should work.

**Comment by kanthoney** [comment]
OK, I'll have a look at doing that.  In the meantime I've uploaded the code as-is to branch `issue_150`.

**Comment by kanthoney** [comment]
I think that's the exhaust plumes fixed in the `issue_150` branch.

**Comment by AnotherCommander** [comment]
Fix confirmed, also with flashers. Awesome job guys.

**Comment by kanthoney** [comment]
I've just tried INTERMEDIATE_CLEAR_DEPTH at 50,000 and the misjoin effect shows up on space stations as well, but not for very long at full speed.  There's a partial fix in branch `two_pass_planet_slice`, but there's still an atmospheric effect I haven't tracked down.

**Comment by AnotherCommander** [comment]
I am closing this issue as fixed. Issue #151 opened to continue discussion on the intermediate clear depth work.
