### ISSUE TITLE
contracts bug - not preseant 

### ISSUE THREAD

**Issue by mimerson** [OoliteProject/oolite#155]
I'm on a mac OS X, with Oolite 1.8
i want to do contracts but they are not present

i have a towbar - but apart from the initial salvage mission have not seen any others - I have salvaged over 50 ships 
i installed the cargo contract mod - and all cargo missions dissapeared - but when uninstalled they returned - with the cobra 3 i'm still not able to take many of these so hoped the mod would help.

also a lot of registered missions are not listed in the OXP - such as long way round. i was hoping to play a lot of the missions

any help or suggestions would be great!

**Comment by cim--** [comment]
Hello mimerson

Towbar and cargo contract mod you'll need to contact the OXP maintainers directly about. The base game intentionally doesn't provide many cargo contracts that a Cobra III can do. Easiest way to contact them is probably through the forum threads for the OXPs
Towbar: http://aegidian.org/bb/viewtopic.php?f=4&t=15204
Cargo Contracts: http://aegidian.org/bb/viewtopic.php?f=3&t=13757

Older OXPs (and most mission OXPs are old) that are not listed in the manager can usually be found on the Wiki in the OXP list there and installed manually. http://wiki.alioth.net/index.php/OXP_List

**Comment by DarthTrader** [comment]
Same thing happened with me, Win 7, version 1.82. All cargo contracts disappeared. When removed the oxp, cargo contracts reappeared

**Comment by AnotherCommander** [comment]
Closing this issue, as it is not core game related.
