### ISSUE TITLE
Speciality cargos disappearing

### ISSUE THREAD

**Issue by DarthTrader** [OoliteProject/oolite#159]
I'm using 1.82 with the latest "New Cargos" oxp, and special cargos tend to turn into regular cargoes when leaving the station. I guess it's a bug.

**Comment by phkb** [comment]
New cargos keeps track of specialty cargos independently of the F8 Market screen, but the cargo has to show up on that screen under one of the standard cargo types. So "TV dinners" get listed as "Food", "Lace" gets listed as "Textiles", and so on. Does that make sense?

**Comment by AnotherCommander** [comment]
So this does not appear to be a core bug, good to close I guess?

**Comment by phkb** [comment]
I think so. If there's a problem with "New Cargos.oxp" it should probably be posted in the BB thread.

**Comment by AnotherCommander** [comment]
Closing as a non-core game issue. DarthTrader, if you want to investgate it further please post under the New Cargoes thread in the Expansion Pack section of the forum.
