### ISSUE TITLE
Combine charts

### ISSUE THREAD

**Issue by CmdrSvengali** [OoliteProject/oolite#162]
Both charts (F6 and F6/F6) provide the same functionality. I guess it makes sense to combine them and their related keys and handlers. Currently if a player zooms out on the SHORT_RANGE_CHART no handler is fired and guiScreen stays as the gui does not change. Same if zooming in on LONG_RANGE_CHART.

**Comment by private-lock** [comment]
I think, this has already been solved ... or is there another way to zoom other than pressing F6 in the chart?

**Comment by phkb** [comment]
Page Up and Page Down do incremental zooms on the chart.
