### ISSUE TITLE
spinModel:false and rotating stations

### ISSUE THREAD

**Issue by CmdrSvengali** [OoliteProject/oolite#168]
The station still rotates, even after latest fix (0cd3b71b1fbd51400cddc226b92fd50cf5ee2eff).

Try *mission.runScreen({model:"[coriolis-station]",spinModel:false});*

**Comment by AnotherCommander** [comment]
Confirmed and, not only it still rotates, but I can see some strobe-light effect on it while it does, which is not present with any other ship.

**Comment by CmdrSvengali** [comment]
On my box it happens with all rotating stations. Smells a bit like matrix fun.

**Comment by kanthoney** [comment]
It's fine on Linux, but with both Windows machines I've tried (one NVidia, one Intel) the station rotates slowly to the left with the strobe lighting.  It's the same for the dodec and rock hermit, but not for normal ships.

**Comment by kanthoney** [comment]
I've fixed the spinning station problem.  I'm not getting strobe lighting on any other rotating stations though, so I'm not sure that's fixed.

**Comment by CmdrSvengali** [comment]
Looks good. Closing .-)
