### ISSUE TITLE
sound issues in windows Vista

### ISSUE THREAD

**Issue by coltx38** [OoliteProject/oolite#173]
3-d sound card in my dell inspiron 1720 running windows vista, yes a downgrade all around but im having sound issues in game not seen on XP or 7 and 10. the sound and or music is extremely choppy but the computer voice (default) is clear. i have done the usual reinstall of sound card and played with settings on card and game with no luck. any ideas?

**Comment by AnotherCommander** [comment]
Two possible solutions:\
1. The easy one: Use the OpenAL32.dll submitted to github just a few days ago to address this specific issue: Link: https://github.com/OoliteProject/oolite-windows-dependencies/blob/master/x86/DLLs/OpenAL32.dll?raw=true
Download it, then replace the OpenAl32.dll in the oolite,app folder with this. I expect this to resolve the issue.

2. Slightly more complex: If the above does not do it, refer to the proposed solution mentioned in this thread: http://www.aegidian.org/bb/viewtopic.php?p=228807#p228807

Please let us know if it works for you.

**Comment by coltx38** [comment]
happy to say that this worked using the OpenAL32.dll thanks.

**Comment by AnotherCommander** [comment]
Thank you for the confirmation. Issue closed.
