### ISSUE TITLE
Wrong value for "capacity" in Trade-goods.plist can cause crash.

### ISSUE THREAD

**Issue by ocz1** [OoliteProject/oolite#174]
Setting `"capacity" = 0;` in **trade-goods.plist** led to a reproducible crash of **oolite ver 1.82** (Windows binary; Win7 x64) 

    {
	"testcommodity" = {
		"name" = "Test good";
		"capacity" = "0"; <--- Source of the crash.
		// Whatever is missing goes in here.
	}
    }    

I'm just guessing, but is it possible, that it is caused by an uncaught division by 0 at a later point?
`adjusted_quantity = (local_capacity / primary_capacity) * primary_quantity;`
See: [Wiki:Trade-goods.plist](http://wiki.alioth.net/index.php/Trade-goods.plist#quantity_adder.2C_quantity_multiplier.2C_quantity_randomiser)

**Comment by AnotherCommander** [comment]
Confirmed and your guess seems correct. Here is the backtrace from the crash, which occurs also in trunk:
```
Program received signal SIGFPE, Arithmetic exception.
0x0000000000665aa1 in -[OOCommodities generateMarketForStation:] (
    self=0xaa9f7c0, _cmd=<optimized out>, station=0xe9fdef0)
    at src/Core/OOCommodities.m:335
335                             q = (q * localCapacity) / baseCapacity;
(gdb) bt
#0  0x0000000000665aa1 in -[OOCommodities generateMarketForStation:] (
    self=0xaa9f7c0, _cmd=<optimized out>, station=0xe9fdef0)
    at src/Core/OOCommodities.m:335
#1  0x00000000004e51fa in -[StationEntity initialiseLocalMarket] (
    self=0xe9fdef0, _cmd=<optimized out>)
    at src/Core/Entities/StationEntity.m:261
#2  0x0000000000689afb in -[Universe reinitAndShowDemo:] (self=0x377b5e0, 
    _cmd=<optimized out>, showDemo=0 '\000') at src/Core/Universe.m:9848
#3  0x000000000048d28a in -[PlayerEntity(LoadSave) loadPlayerFromFile:asNew:]
    (self=0x41140d0, _cmd=<optimized out>, fileToOpen=0x3de9850, 
    asNew=1 '\001') at src/Core/Entities/PlayerEntityLoadSave.m:646
#4  0x000000000048bbde in -[PlayerEntity(LoadSave) startScenario] (
    self=0x41140d0, _cmd=<optimized out>)
    at src/Core/Entities/PlayerEntityLoadSave.m:345
#5  0x000000000046b909 in -[PlayerEntity(OOControlsPrivate) pollDemoControls:]
    (self=0x41140d0, _cmd=<optimized out>, delta_t=<optimized out>)
    at src/Core/Entities/PlayerEntityControls.m:4143
#6  0x000000000046885e in -[PlayerEntity(Controls) pollControls:] (
    self=0x41140d0, _cmd=<optimized out>, delta_t=0.015999972820281982)
    at src/Core/Entities/PlayerEntityControls.m:383
#7  0x0000000000000000 in ?? ()
```

**Comment by AnotherCommander** [comment]
The crash has been now fixed, but there is still something wrong in the test good setup for certain values of capacity. Using a capacity of 13, for example, seems to cause buggy behaviour when trying to buy or sell the test good. Further investigation is required.

**Comment by AnotherCommander** [comment]
Closing this one as it specifically refers to a crash that is fixed. A new issue has been opened to address the unexpected behaviour of the capacity property in trade-goods.plist.
