### ISSUE TITLE
missile_role in shipdata.plist

### ISSUE THREAD

**Issue by CmdrSvengali** [OoliteProject/oolite#178]
If an AddOn defines the missile_role in shipdata.plist I'd expect that this entity really gets this type of missile. Currently there is a chance that Oolite uses different ones which renders this key nearly useless.

**Comment by CmdrSvengali** [comment]
Wouldn't it make sense to check the auto_weapons setting for the random thingummie?

**Comment by AnotherCommander** [comment]
Proposed fix for this issue below. With auto_weapons set, the code behaves like before, without auto_weapons it never attempts a random selection. I am trying to avoid any changes to existing behaviour regarding invalid missile_role handling etc., except for the very first time the selection is made. Changes are marked with <----. Please review and advise in case I have missed something.
```
- (OOEquipmentType *) selectMissile
{
	OOEquipmentType		*missileType = nil;
	NSString			*role = nil;
	double				chance = randf();
	BOOL				thargoidMissile = NO;
	
	if ([self isThargoid])
	{
		if (_missileRole != nil) missileType = [self verifiedMissileTypeFromRole:_missileRole];
		if (missileType == nil) {
			_missileRole = @"EQ_THARGON";	// no valid missile_role defined, use thargoid fallback from now on.
			missileType = [self verifiedMissileTypeFromRole:_missileRole];
		}
	}
	else
	{
		// All other ships: random role 10% of the cases when auto weapons is set, if a missile_role is defined.
		// Without auto weapons, never random.//<----
		float initialSelectionRandomness = chance;  //<----
		if(![self hasAutoWeapons])  initialSelectionRandomness = 0.0f; //<-----
		if (initialSelectionRandomness < 0.9f && _missileRole != nil) //<-----
		{
			missileType = [self verifiedMissileTypeFromRole:_missileRole];
		}
		
		if (missileType == nil)	// the random 10% , or no valid missile_role defined
[...]
```
