### ISSUE TITLE
Atmospheric Fog Not Working Correctly With Shaders Enabled

### ISSUE THREAD

**Issue by AnotherCommander** [OoliteProject/oolite#181]
As the title says, the fog effect seen in the atmosphere does not seem to work correctly. More specifically, although it is apparently applied to the stars, which fade away as we enter the atmosphere, the objects, like stations, asteroids etc. do not seem to be subject to the same rules when shaders are enabled. All seems to work ok on detail level Normal Detail and below, but broken in Shaders Enabled and Extra Detail. The images below show the Lave Coriolis, as seen from within the atmosphere very close to the planet's surface. The first one is at Normal Detail, the second one is at Shaders Enabled. The station is clearly visible in the second shot, when it really shouldn't be.
![fogbug01](https://cloud.githubusercontent.com/assets/623526/13200028/a33eef54-d838-11e5-8e35-24ea9a5d5aec.jpg)

![fogbug02](https://cloud.githubusercontent.com/assets/623526/13200030/aacca392-d838-11e5-90c3-0467eb7de39f.jpg)

**Comment by kanthoney** [comment]
From the [OpenGL spec](https://www.opengl.org/registry/doc/glspec45.compatibility.pdf), page 584

>Fog has no effect if a fragment shader is active.

I'm sure I've got a book somewhere round here that explains how to do fog in a fragment shader.  I'll try and dig it out.

**Comment by kanthoney** [comment]
I suspect it's not that difficult.  We'd add a `vec4 uFogColor` uniform to the fragment shader with the first three components being the atmosphere colour and the alpha component being used for the blend factor (0 for no fogging, 1 for total fogging).  Then the final line in the fragment shader would be

```
gl_FragColor = uFogColor.w * vec4(uFogColor.xyz, 1.0) + (1.0-uFogColor.w)*totalColor;
```

Then it's a matter of working out what the blend factor is and uploading the uniform for each object. I'm currently chasing through the code to find out how Oolite uploads uniforms, which looks quite complicated.

**Comment by kanthoney** [comment]
See branch shader_fog for a possible fix.

**Comment by AnotherCommander** [comment]
Tested the branch on the NVidia 9600GTM laptop. The fog is now applied correctly and the primary objective of the fix attempt has been achieved, but (you knew there was a but coming, I'm sure ;-)) there seems to be something funny going on with the lighting at the exact moment the fog stops being applied. The shots below explain it better:

Here we are at the atmosphere boundary. See the station lighting, it appears to be bright.
![fogbug03](https://cloud.githubusercontent.com/assets/623526/13205185/2e3c6ccc-d8e2-11e5-959f-7be123c51ea3.jpg)

And here is just after we've left the atmosphere, just a couple meters closer to the station. There is a jump in the light from bright to much less bright.
![fogbug04](https://cloud.githubusercontent.com/assets/623526/13205193/694745c6-d8e2-11e5-843c-8aa0a5d5a219.jpg)

I've seen a couple of rgb color definitions in thef fix commit along the lines of drawthing setAtmosphereFogging: [OOColor colorWithRed: skyClearColor[0] green: skyClearColor[1] blue: skyClearColor[3] alpha: fog_blend]];
I see no skyClearColor[2] mentioned anywhere. Is this intentional?

**Comment by AnotherCommander** [comment]
... and commit 305fd3aa has apparently fixed the lighting issue. Good job Kevin.

**Comment by kanthoney** [comment]
No, the 3 should be a 2.  I just forgot how to count!

**Comment by AnotherCommander** [comment]
Tested and confirmed working on an Intel HD card as well.

The only thing I couldn't do is modify the fragment shaders of one of Griff's shaders to confirm that it all works also with OXPs. Attached are the three fragment shaders of the Griff's Dodo I use
[GriffDodoFragShaders.zip](https://github.com/OoliteProject/oolite/files/140362/GriffDodoFragShaders.zip)

. I just added the uFog uniform line and changed the gl_FragColor final line to match what we have in the updated shader. I couldn't get it to work, but then again I am not sure whether my modifications are ok or not (kind of hard when there is apparently no proper way to debug shaders).

**Comment by AnotherCommander** [comment]
OK, it works also with OXPs. In the case of the Griff Dodo, I was not passing the unifrom fogUniform in the shaders->uniforms section of shipdata.plist. I think it works fine and is ready for merge.

**Comment by kanthoney** [comment]
I'm fine with a merge if you're happy.

**Comment by AnotherCommander** [comment]
Issue resolved by merging of the shader_fog branch (commits f10b043 & 8e06d2e - I screwed up a bit by initially merging an earlier version of the branch which did not have all the fixes in, but hopefully should be OK now). Great job, Kevin.
