### ISSUE TITLE
Starboard laser sound not played

### ISSUE THREAD

**Issue by CmdrSvengali** [OoliteProject/oolite#182]
The starboard laser sound is not played or silent in v1.82 and current trunk. All other (front, rear and port) are ok.

**Comment by AnotherCommander** [comment]
Is there a specific laser or equipment configuration that does it? It works fine for me here on trunk and with various savefiles, as well as OXPs enabled / disabled.

**Comment by CmdrSvengali** [comment]
32bit version, vanilla Oolite (test-version, not deployment), no AddOns, fresh Jameson. It doesn't matter if it's a Pulse, Beam or Military laser.

**Comment by AnotherCommander** [comment]
Nope, cannot reproduce here. Anyone else?

**Comment by stimer** [comment]
I just try load any save on my v1.83 (master branch) - and buy pulse laser on starboard - yes - no sound.
(Linux)

**Comment by kanthoney** [comment]
Working fine on Linux here. The sound does only appear in the right speaker though (left for the port laser), so maybe you're only hearing one channel.

**Comment by stimer** [comment]
oh... yep - I use mono ear-phone-set *confused*
I check in mixer - sound exists.
sorry - I just tried to help )

**Comment by CmdrSvengali** [comment]
Sorry for the hazzles. One of the speakers died on my Laptop. Haven't noticed it before as I'm usually playing plugged into the surround rig. Closing.
