### ISSUE TITLE
Police to aggresive

### ISSUE THREAD

**Issue by DTHP** [OoliteProject/oolite#188]
If you read the documentation then the police is not supposed to attack you if you are only an Offender.
in fact they should give you limited protection. Instead they attack you. Even with a bounty of only 1.

**Comment by phkb** [comment]
Police will attack at different levels of offender, based on the system government. The calculation to work out the maximum bounty (that is, the difference between fining and attacking) is:
   50 - (system.info.government * 6)
So if the player has a bounty of (say) 10, the police will only fine them in an Anarchy system (50 - (0 * 6) = 50), but will attack them in Corp States (50 - (7 * 6) = 8). 
To help reproduce the issue, which system were you in when you were attacked by police? Do you have any OXP's installed that might impact on the way bounties are calculated or how police might react? (eg Anarchies.oxp, BountySystem.oxp)

**Comment by DTHP** [comment]
It was Ensoreus, i had a bounty of only 1. There is no OXPs installed that affects behaviour or bounty, only a HUD oxp that I'm fiddeling with atm.

# 82. Ensoreus (52,224), {17,31,90,154,157,201,244} within 7.0 LY. Radius 3380 km.
Corporate State, Rich Ind. Pop. 5.2 B, Prod. 45760 MCr. HC: 7, TL: 12, Black Fat Felines.
This planet is a tedious little planet.

I tried to reproduce it by setting it manually, but now i only get fined.

Either way the documentation does not explain it well enough that as an offender and not a fugitive, you can still be attacked. If you read that, you get the impression that as an offender you have limited protection as there is no way for the player to know how many offender/bounty points he has unless ofcourse he installs some sort of OXP that tells him that.

**Comment by phkb** [comment]
Documentation might certainly need a clean up. Which page in particular did you note the confusing info? I've done a bit of searching but I can't find the specific reference to what you mentioned. Not saying it's not there, just that I can't find it myself!

**Comment by AnotherCommander** [comment]
The documentation referred to is the Reference Sheet, Legal Status paragraph under General Information. We needed to do an update to the Reference Sheet anyway, so this was a good chance to do it. The comment referring to the Offender status has been updated to reflect the fact that an offender cannot be considered safe from Police attacks. This should be sufficient to close the issue,
