### ISSUE TITLE
Improvements to atmosphere shaders

### ISSUE THREAD

**Issue by AnotherCommander** [OoliteProject/oolite#197]
Commander_X has been kind enough to share with me his work on a new atmosphere shader. I am bringing this here, with his permission, to showcase it - because I think it is a really good attempt - and maybe motivate others to give their feedback and maybe contribute in its completion. This could be the first post-1.84 feature.

As you can see in the pics below, this shader improves the visuals of the atmosphere effects at the planet edges. It will cause the effect to fade out when too close or too far from the planet. From what I have seen, the effect is really good when close to the planet, but could be further improved in the far-away case. In my opinion it works better for lower values of ambient lighting levels.

The shader files + code patch to apply these changes are also attached in this report. Please have a look and your feedback is welcome.

Note: The first pic is with the unchanged shader, as provided by Commander_X, the second one is with a slight modification on my part to bias the atmosphere color slightly towards blue.
![atmoshader01](https://cloud.githubusercontent.com/assets/623526/16713129/d42628fc-469d-11e6-86b8-7410c6a77fc2.jpg)
![atmoshader02](https://cloud.githubusercontent.com/assets/623526/16713133/de945b42-469d-11e6-98ba-a5bbac9b11bd.jpg)
[AddOns.1.84.zip](https://github.com/OoliteProject/oolite/files/355997/AddOns.1.84.zip)
[atmExposed.1.84.diff.zip](https://github.com/OoliteProject/oolite/files/355998/atmExposed.1.84.diff.zip)

There is also a video of the shader provided, see here: https://drive.google.com/open?id=0B-H82JXdVEApUnhIaWNMRVU1bXc

**Comment by kanthoney** [comment]
That looks pretty darned good! Could you create a branch for that?

**Comment by AnotherCommander** [comment]
Issue closed. The new atmospheres entered trunk with commit 9e11210.
