### ISSUE TITLE
1.84 doesn't compile

### ISSUE THREAD

**Issue by svenstaro** [OoliteProject/oolite#200]
My system: Arch Linux, gcc 6.1.1, oolite 1.84 (source download), gnustep-back 0.25.0, gnustep-base	1.24.9. Log attached.

What I did: `make -f Makefile release-deployment`

[log.txt](https://github.com/OoliteProject/oolite/files/383728/log.txt)

**Comment by KonstantinosSykas** [comment]
Could you, please, try the following?
`make -f Makefile distclean`
`make -f Makefile deps-release-deployment`

**Comment by svenstaro** [comment]
With your commands I get this: [log.txt](https://github.com/OoliteProject/oolite/files/389598/log.txt)

**Comment by kanthoney** [comment]
I'd try an older version of gcc.  Install the gcc5 package and try

    CC=gcc-5.4 make -f Makefile release-deployment

**Comment by svenstaro** [comment]
With gcc-5: 
[log.txt](https://github.com/OoliteProject/oolite/files/390470/log.txt)

**Comment by KonstantinosSykas** [comment]
If it is not much of a trouble for you, could you please backup the `jsapi.cpp` and `jsfun.cpp` files and perform the following changes. Then try to build again.

We have noticed that in later versions these inconsistencies have been addressed. 
We are using this old version to be able to have a common build mechanism between Windows and Linux platforms.

- jsapi.cpp - Change line 3980 to return null pointer
``` 
3979: if (!GetPropertyNames(cx, obj, JSITER_OWNONLY, &props) || !VectorToIdArray(cx, props, &ida))
3980:         return NULL;
3981: for (size_t n = 0; n < size_t(ida->length); ++n)
3982:         JS_ASSERT(js_CheckForStringIndex(ida->vector[n]) == ida->vector[n]);
```

- jsfun.cpp - Change line 2055 to return null pointer
``` 
2053: JSString *str = JS_DecompileFunction(cx, fun, indent);
2054: if (!str)
2055:         return false;
2056: 
2057: if (!indent)
2058:         cx->compartment->toSourceCache.put(fun, str);
```

- jsfun.cpp - Change line 2661 to return null pointer
``` 
2657: jsid id = ATOM_TO_JSID(cx->runtime->atomState.classPrototypeAtom);
2658: const Shape *shape = funobj->nativeLookup(id);
2659: if (!shape) {
2660:      if (!ResolveInterpretedFunctionPrototype(cx, funobj))
2661:              return false;
2662:      shape = funobj->nativeLookup(id);
2663: }
```

**Comment by svenstaro** [comment]
Could you make a patch for me so I can apply it in my PKGBUILD please?

**Comment by KonstantinosSykas** [comment]
[spidermonkey185-ff4_patch.zip](https://github.com/OoliteProject/oolite/files/394404/spidermonkey185-ff4_patch.zip)

**Comment by svenstaro** [comment]
Given the patch, I also get errors: [log.txt](https://github.com/OoliteProject/oolite/files/400935/log.txt)

**Comment by KonstantinosSykas** [comment]
This looks like the same root-cause but for a different file this time. 
It seems that you are still compiling with GCC 6. I quote:

_(source https://gcc.gnu.org/gcc-6/porting_to.html)_
> **Cannot convert 'bool' to 'T*'**
>
> The current C++ standard only allows integer literals to be used as null pointer constants, so other constants such as false and (1 - 1) cannot be used where a null pointer is desired. Code that fails to compile with this error should be changed to use nullptr, or 0, or NULL.

I do not have the means to replicate the case, in order to pinpoint all the cases where the SpiderMonkey fails this constraint.

I would highly appreciate if you continue by performing the remaining changes, where this specific error occurs, and just share here a log of the filenames and lines changed in order to see if we can come up with a single patch.

If you know how to locate and change the problematic 'return false;' to 'return NULL;' then you may ignore the following instructions.

Step 1. In the build log search for the word `error:`. You will find something like that:
```
../jsiter.cpp: In function 'JSObject* NewIteratorObject(JSContext*, uintN)':
../jsiter.cpp:428:20: error: cannot convert 'bool' to 'JSObject*' in return
             return false;
                    ^~~~~
```
Step 2. As long as the error is that it cannot convert the boolean to a pointer, then note the filename (`jsiter.cpp` in this case) and the line number (428 in this case).

Step 3. Navigate to `deps/mozilla/js/src` and execute the following command, using the relevant filename and line number each time:
`sed -i'' '428s/false/NULL/' jsiter.cpp`

Let us know how it went.

**Comment by KonstantinosSykas** [comment]
... on the other hand, perhaps the gnu.org link above, already gives the solution. 
If you use the `-std=gnu++98` parameter, might do the trick.

This is a patch for the SpiderMonkey file `js/src/Makefile.in`.

[spidermonkey185ff4-GCC6.zip](https://github.com/OoliteProject/oolite/files/401945/spidermonkey185ff4-GCC6.zip)

**Comment by svenstaro** [comment]
That patch makes it compile! However, I still need `sed -i "/ADDITIONAL_OBJCFLAGS/s/=/= -fobjc-exceptions/" GNUmakefile` which is something you might want to fix.

**Comment by KonstantinosSykas** [comment]
I'm glad it worked for you. 
However, we still find it strange that you need to explicitly add the `-fobjc-exceptions` flag; gnustep-make should automatically do this for you.

We have discussed this internally and we have a probable scenario for this to happen, but we need some more info to be sure.
If it is not too much of a fuss for you, please, share the `common.make` file and your environment variables; both from the build environment used to build Oolite.

**Comment by AnotherCommander** [comment]
The JS makefile fix has gone into the Arch repos already and no response has arrived from @svenstaro. Will leave open for a couple more days in case of feedback to the question above, then will close as fixed.

**Comment by KonstantinosSykas** [comment]
As far as it concerns the GNUmakefile patch, having checked in the [Arch Linux community.git repository for gnustep-make](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/gnustep-make&id=160adf3fcebeaa2f1e603af754b3fe869e3dd374), it seems that the `--enable-native-objc-exceptions` option is now added in the `gnustep-make 2.6.8-3`. Therefore, the GNUmakefile patch may now be obsolete.

**Comment by AnotherCommander** [comment]
OK, I believe we can close this now as fixed.

**Comment by svenstaro** [comment]
Well I still get `src/Core/Entities/PlayerEntityControls.m:358:2: error: '-fobjc-exceptions' is required to enable Objective-C exception syntax` with the newest version of gnustep-make.
