### ISSUE TITLE
[FR] Frame-Limiter - can't play with this quite recent laptop

### ISSUE THREAD

**Issue by joemaro** [OoliteProject/oolite#206]
is a frame-limiter possible?
i use a quite recent gaming laptop and running oolite is just heating the CPU too much, while rendering 300fps.
Lowering the gfx details doesn't do the job because it will continue to render as much as possible.
Is there maybe another way of tackling this?
Would love to really try your game!
Thanks for taking the time to respond!

**Comment by AnotherCommander** [comment]
What OS are you using? On Windows and Linux, Oolite tries to set Vsync when it starts up so you normally should be getting FPS equal to your monitor's refresh rate.  For various reason, (mostly the related OpenGL extension missing from your gfx card's drivers), this might fail. However, 300 FPS seems too much. The game is set to render at maximum 200 FPS so  I am not sure what exactly is going on there.

In any case, try editing your .GNUstepDefaults file  and add this line inside the "oolite" section, to limit your FPS to the desired number (60 in the example below):
```
animation_timer_interval = 0.0167;
```
You need to use a value of 1.0/desiredFPS.
Hope this helps.

**Comment by joemaro** [comment]
Hey! Thanks a lot for the reply!
Sorry didn't mention details: Manjaro Linux (arch based) running it on the intel part of a optimus system (the nvidia part doesnt work well for me under linux, but that doesnt matter here)

So i added your recommendation but haven't succeeded yet, maybe because the file you mentioned is a XML file, so i tried to add a key like this
        <key>animation_timer_interval</key>
        <real>0.0167</real>
but didn't notice any change ingame (still lots of cpu-power needed)

I edited the file that comes with oolite and is inside "GNUstep/Defaults".

Thanks again!
