### ISSUE TITLE
Error when accessing F8 screen while docked in interstellar space

### ISSUE THREAD

**Issue by phkb** [OoliteProject/oolite#210]
I was in interstellar space recently and happened upon a Navy vessel, which I docked at to refuel. Then, because I thought it might be interesting, I went to the F8 screen to see if any of the goods I was carrying might have good value out here.

I got a blank screen, other than my HUD. No title, no Xenon UI background - just black. And in my log file I found these entries, one for each time I pressed F8.
```
17:09:59.352 [exception]: ***** Exception in pollDockedControls [GUI keys]: NSInvalidArgumentException : Tried to init dictionary with nil value
17:10:02.681 [exception]: ***** Exception in pollDockedControls [GUI keys]: NSInvalidArgumentException : Tried to init dictionary with nil value
17:10:06.914 [exception]: ***** Exception in pollDockedControls [GUI keys]: NSInvalidArgumentException : Tried to init dictionary with nil value
```

**Comment by AnotherCommander** [comment]
Please try with the latest fix attempt and let us know if it resolved the issue. Remember to test docked/undocked, main/non-main station, standard space / witchspace scenarios.

**Comment by phkb** [comment]
Well, my quick-pass test of all those scenarios has worked successfully. I'll do a longer test tonight. Thanks a_c!

**Comment by phkb** [comment]
Longer test went fine, no errors. I'm going to call this closed!
