### ISSUE TITLE
Javascript event "viewDirectionChanged" not raised during a witchspace jump.

### ISSUE THREAD

**Issue by phkb** [OoliteProject/oolite#212]
During a witchspace jump the view direction is changed to be the forward view. However, the Javascript event "viewDirectionChanged" is not called when the change takes place.

**Comment by AnotherCommander** [comment]
Following a basic test run, I think this is now fixed. @phkb : Can you please give it one more test?

**Comment by AnotherCommander** [comment]
Closing the issue based on this post in the forum: http://www.aegidian.org/bb/viewtopic.php?p=252834#p252834
