### ISSUE TITLE
Errors in log when accessing shipyard in Interstellar space

### ISSUE THREAD

**Issue by phkb** [OoliteProject/oolite#213]
Using the "Tionisla Reporter" OXP, I docked at the station in interstellar space and went to the shipyard screen (F3 F3). No ships were available for purchase. However, in my log file I saw these errors:
`12:37:13.735 [system.description.error]: '0 -1' is an invalid system key. This is an internal error. Please report it.`
`12:37:13.735 [exception]: ***** Exception in pollDockedControls [GUI keys]: NSInvalidArgumentException : Tried to add nil value for key 'current_system_name' to dictionary
`

**Comment by AnotherCommander** [comment]
Please test the fix just committed. I tried to make it as less intrusive as I could.

**Comment by phkb** [comment]
All tested OK. No errors reported when accessing shipyard in interstellar space! Right on, commander!
