### ISSUE TITLE
System Data Screen Bug w/ Nova System

### ISSUE THREAD

**Issue by AnotherCommander** [OoliteProject/oolite#225]
This is a bug that exists both in current trunk and also in 1.84. It involves the system data screen for a system gone nova and, more specifically, the behaviour when a route containing a nova system has been planned and the F7 screen is examined for each system on the way using the next/previous system keys.

This is how to reproduce: 
1. Have a nova system handy. You can use the savegame from [main source tree]\tests\Checklist-files\Missions\Nova.oolite-save, which is ready to go.  Have also the Nav Array available.
2. Have a route involving that system planned. Here is an example:
![f7bug03](https://cloud.githubusercontent.com/assets/623526/26403883/2d909886-4090-11e7-8890-581c7a943ae5.jpg)
3. Start going through the systems in the F7 screen. All of them are shown OK, but for the Nova system we get a decription without a background, contrary to what we would have hoped for:
![f7bug02](https://cloud.githubusercontent.com/assets/623526/26403917/5674a508-4090-11e7-8e65-84c73d452557.jpg)
4. It gets even better. Now set the route to two systems only, the one you are in and the nova one.
![f7bug04](https://cloud.githubusercontent.com/assets/623526/26403982/9ba9d6d4-4090-11e7-8583-4c42ed4fe5b2.jpg)
5. Go again to F7 and play with the prev/next system keys. Look what happens when you get to the second system after you have passed through the nova system:'s F7 screen:
![f7bug01](https://cloud.githubusercontent.com/assets/623526/26404006/b4e96e0c-4090-11e7-8e68-961bb2445f7a.jpg)
Looks cool, but I guess we can call this a bug. It seems that the background image for the nova system is not generated properly nor cleaned up properly when we are in the next/previous system F7 mode.

**Comment by kanthoney** [comment]
Hopefully fixed with https://github.com/OoliteProject/oolite/commit/3e3e528556f4ddb1bbcd7a2ce6e46dd25862dc6e.

**Comment by AnotherCommander** [comment]
Fix confirmed. After the little modification fixing the conflicting types warning on GCC 4.7.1,, I think we are good to close this one.

**Comment by AnotherCommander** [comment]
Reopening issue. The fix at commit 3e3e528.seems to have broken somwthing in the normal backgrounds logic. Just tried with BGS 2.0 installed and when I set up a planned route, this is what happens:
- The first planet shown as soon as F7 is hit has the correct BGS background.
- All other planets along the route have a black background (no BGS stuff anymore).

**Comment by kanthoney** [comment]
Didn't mean to close this - Github trying to be clever, I think.

**Comment by kanthoney** [comment]
The latest fix appears to work except the Nova sun is lost if the BGS Library OXZ is installed. I suspect we'll have to change the `guiScreenChanged` javascript method to include the refresh parameter to make that work.

**Comment by AnotherCommander** [comment]
With BGS installed, I see the same symptoms as when origianlly reporting the issue. I can confirm the BGS sun lost from the F7 screen and also, with just two planets in a route (one being the nova system), this is what happens:
![issue225_02](https://cloud.githubusercontent.com/assets/623526/26508427/ffa5112e-4254-11e7-8e9f-ef31cc67b131.jpg)
![issue225_01](https://cloud.githubusercontent.com/assets/623526/26508436/036810a4-4255-11e7-8a39-8f83e99ce286.jpg)

**Comment by AnotherCommander** [comment]
Same with the Red Set. The nova background takes the place of the standard F7 screen background.
![issue225_03](https://cloud.githubusercontent.com/assets/623526/26509396/dea4004e-4258-11e7-896b-88da67d595c0.jpg)

**Comment by kanthoney** [comment]
I think the problem is line `9854` in `PlayerEntity.m`:

```
ShipScriptEvent(context, self, "guiScreenChanged", OOJSValueFromGUIScreenID(context, toScreen), OOJSValueFromGUIScreenID(context, fromScreen));
```

Because toScreen and fromScreen are the same, the background isn't being updated. I guess we need to add in the refresh parameter to tell scripts to refresh the backround even when we're still on the same screen, and then update OXP's to use the parameter.

**Comment by AnotherCommander** [comment]
The update OXPs part is the tricky one. During earlier tests today, I saw that when we are switching through the planets in a route on fhe F7 screen, guiChanged is always 0. What if we checked the system we are switching to and, if it is a nova, issue a gui changed notification? In other words, treat the nova data as a different gui screen that calls into setGuiToSystemData and sets the background accordingly? I admit it is a bit messy. but I am not sure which way is better: updating core in a kind of messy way or update all OXPs that use backgrounds? Would that even have a chance of working?

**Comment by kanthoney** [comment]
I'll have to sleep on that one I think.  At the moment I think the neatest solution would be to add a `backgroundChanged` event, but that would require OXP rewrites.

**Comment by AnotherCommander** [comment]
I think the fix in fba8c96 is actually a good one. I had a look at the Library 1.1. code and there is this in his.guiScreenChanged:
```
case "GUI_SCREEN_SYSTEM_DATA":
	var inf = System.infoForSystem(galaxyNumber,player.ship.targetSystem),sp = 0;
	if(inf.sun_gone_nova || inf.sun_going_nova) sp = 1;
	this.$op = null;
	this._setGUI(gu,sp);
	break;
```
Changing it to 
```
case "GUI_SCREEN_SYSTEM_DATA":
	var inf = System.infoForSystem(galaxyNumber,player.ship.infoSystem),sp = 0;
	if(inf.sun_gone_nova || inf.sun_going_nova) sp = 1;
	this.$op = null;
	this._setGUI(gu,sp);
	break;
```
fixes it completely for me. Kevin, if you can confirm, I think we should be able to close this. Library OXP and any OXP that uses targetSystem where infoSystem is intended will have to be updated accordingly.

**Comment by kanthoney** [comment]
That fixes BGS for me.  If I remove BGS and leave Library installed the Nova sun disappears, but I guess we'd expect that - Library overrides the backgrounds without actually replacing them with anything.

**Comment by AnotherCommander** [comment]
In this case, I think we've done all we could from our side. I believe we can close this issue.
