### ISSUE TITLE
fullscreen is greater than screen size, becoming a small viewport into the normal view

### ISSUE THREAD

**Issue by myxomycophyta** [OoliteProject/oolite#226]
This effect has been verified to be consistent across the following versions:
Oolite-1.73.4-test.exe
Oolite-1.80_x64.exe
Oolite-1.84_x64.exe
Oolite-1.84_x86.exe

I toggle full screen mode on/off with F12.

My HP Pavilion dv7 Notebook PC HW and SW are summarized in the attached WindowsSystemInfo.txt file.  Standard configuration is a two monitor system, with the laptop monitor at 1600x900 resolution, and the external VGA monitor at 1920x1080 resolution.

The full screen image (across the two monitors) is represented in the attached FullScreenShot.png file.  This file is not an exact replica, because the two monitors are not the same size, yet the image is rectangular.  Windows Prt Scrn places blank space above the left hand screen.  Otherwise it is an accurate representation of the user view across the two monitors.

Try to replicate the effect when both monitors use the same resolution:
This effect IS repeatable running Oolite-1.84_x64.exe on the same PC with both monitors set to identical 1600x900 resolution.

Try to replicate the effect on a single monitor system:
This effect is NOT repeatable running Oolite-1.84_x64.exe on the same PC using only a single monitor.

Try to replicate the effect on another dual monitor PC:
This effect is NOT repeatable running Oolite-1.84_x64.exe on a HP Envy TS 17 Notebook PC.

This seems like a very low priority bug, because it may be unique to one hardware setup, and also full screen mode is nice but not absolutely essential, since a window at full size is nearly identical to full screen mode.  Also, my old hardware is probably due for an update before too long (whenever something breaks).  This bug report is provided for information only, without expectation of resolution.

<img width="1760" alt="fullscreenshot" src="https://cloud.githubusercontent.com/assets/29023305/26531478/d9e0732a-43b7-11e7-9b96-591bcbbb34a8.png">
[WindowsSystemInfo.txt](https://github.com/OoliteProject/oolite/files/1034429/WindowsSystemInfo.txt)

**Comment by myxomycophyta** [comment]
Try to replicate the effect on another dual monitor PC:
This effect is also NOT repeatable running Oolite-1.84_x64.exe on a Dell Inspiron One 2330 with a second monitor.

**Comment by AnotherCommander** [comment]
You seem to be running this driver version: 8.832.0.0. This is dated early 2011.

Looking at the AMD site for latest HD 652G driver, it is on version 13.152.0.0, dated 2013-09-08. You could try installing and testing with this driver.

When writing the fullscreen updates code, I had tested it with NVidia 9600GTM and Intel HD. Both were functioning correctly with dual monitor setups.

As a side note, with 1.84, you oould also try moving the game window to the other monitor and switching to fullscreen. 1.84 can detect which monitor it is running on and will switch fullscreen there (all previous versions were switching fullscreen to the primary monitor no matter where the game window was at the time of the switch).

Hope this helps.

**Comment by AnotherCommander** [comment]
This issue was closed by its originator, but it looks like it was a duplicate of #229, which has now been resolved with commit ab0302d. @myxomycophyta : If you want, try installing and running nightly ab0302d once it becomes available for download. If you use high-DPI scaling on any of your two monitors, I would expect your fullscreen issues to be resolved with that build.
