### ISSUE TITLE
planetary data not displayed after quite a while of playing on oolite-trunk-1.85.0.412349f-dev.x64.exe

### ISSUE THREAD

**Issue by myxomycophyta** [OoliteProject/oolite#228]
I loaded 822.oolite-save into Bemaera.  It didn't occur to me to check F7.  I launched and flew to Ensoreus.  After repairing the ship and purchasing a quantum cascade mine, I prepared to fly to the next system of interest using F6 and F7.  I noted that F7 failed to display system information (refer to screenshot.png).

This has happened in the past, but a reinstallation of oolite-trunk-1.85.0.412349f-dev.x64.exe fixed the problem.  

I closed and reopened the development version, and loaded the saved game, noting that the problem persisted.

I closed and reopened the development version, and started with a new commander, noting that the problem persisted.

I closed the game.

I opened Windows System Info and initiated a save, then reopened the development version and continued playing, carrying a cargo of computers into Ararus. 

After saving, I quit and then opened oolite-trunk-1.85.0.412349f-dev.x64.exe to reinstall the program.

I selected Finish/Run.

I loaded my most recent save game file and hit F7.  Planetary data was now visible.

Now that I have reinstalled the game, the problem is not repeatable.  When it occurred, though, it was persistent.

I closed the program and loaded Oolite-1.84_x64.exe, starting a new commander.  Planetary data on Lave is visible.

I loaded the most recent save game file over my new commander.  Planetary data is visible.

So, this is the second time I've experienced this bug on the development version, and, like last time, reinstallation cured the problem.

The truth is, there's a work around, and this only occurs with the development build, so personally I understand that this is not a high priority issue.

However, if this pops up again, is there something else I can do to collect data that could be more helpful?

Thanks!

[systeminfo.txt](https://github.com/OoliteProject/oolite/files/1043246/systeminfo.txt)

<img width="1760" alt="screenshot" src="https://cloud.githubusercontent.com/assets/29023305/26659325/d4d19dd6-463d-11e7-90ca-526eac3ab9ca.png">

[Previous.txt](https://github.com/OoliteProject/oolite/files/1043249/Previous.txt)
[Latest.txt](https://github.com/OoliteProject/oolite/files/1043250/Latest.txt)

Surprisingly, this system does not support uploading "oolite-save" files.  Below, I have changed the last two save game files to end in ".txt"

[821(newest).oolite-save.txt](https://github.com/OoliteProject/oolite/files/1043252/821.newest.oolite-save.txt)
[822(older).oolite-save.txt](https://github.com/OoliteProject/oolite/files/1043253/822.older.oolite-save.txt)

**Comment by myxomycophyta** [comment]
The screenshot is of a dual monitor system with Oolite on the left monitor, and Paint, sporting a previous screenshot, on the right monitor.  As you can see, planetary data that would normally display in yellow is absent.

**Comment by myxomycophyta** [comment]
somehow it seems that i accidentally closed this issue.  (sorry!)  I see now that "Close and comment" means close the issue, not, like, "Close this section and go back to the top of GitHub."  LOL  oops!

**Comment by phkb** [comment]
Can you check the "descriptions.plist" file and make sure the additional lines from #224 are present?

**Comment by AnotherCommander** [comment]
The missing information is a symptom of using an older descriptions.plist with the newest executable. Were there any OXPs installed when this happened? (My guess is no, judging from the two log files, but even a Config folder under AddOns with a previous description.plist inside it could cause this).

When this happens, the log registers an entry similar to this:
```
10:50:11.989 [strings.expand.invalidData]: ***** ERROR: String expansion value <GSArray 0x6bbafc8> for [inhabitants] from descriptions.plist is not a string or number.
10:50:11.989 [strings.expand.warning.unknownExpansion]: ----- WARNING: Unknown expansion key [inhabitants] in string.
10:50:11.989 [strings.expand.warning.unbalancedClosingBracket]: ----- WARNING: Unbalanced ] in string.
```
If you see this again, exit the game immediately and check the Latest.log file for the above message at the end. The most likely reason that a re-install of the game fixes it is because it restores the correct descriptions.plist. I have been able to repeat the actions you described with 822.oolite-save without any problems or log errors and with the same trunk version.

**Comment by myxomycophyta** [comment]
> Can you check the "descriptions.plist" file and make sure the additional lines from #224 are present?

I think this means, open the file at C:\Oolite-Trunk\oolite.app\Resources\Config\descriptions.plist and see if there are any lines after #224.  Yes, there are lines after #224.  Here is that file:
[descriptions.plist.txt](https://github.com/OoliteProject/oolite/files/1046322/descriptions.plist.txt)

> Were there any OXPs installed when this happened?

No.

> ...even a Config folder under AddOns with a previous description.plist inside it could cause this

OK, that may be the problem.  I defined a custom keyboard interface in the file at Oolite-Trunk\AddOns\Config\keyconfig.plist.  Here is that file:
[keyconfig.plist.txt](https://github.com/OoliteProject/oolite/files/1046324/keyconfig.plist.txt)

> When this happens, the log registers an entry similar to this...
> If you see this again, exit the game immediately and check the Latest.log file for the above message at the end.

Today upon start-up this happened again, so I immediately exited through F2, then checked the Latest.log, but couldn't find these messages.  I searched the Latest.log for "ERROR" and "WARNING" but only found errors and warnings about failed packets.  Here is that Latest.log file:
[Latest.log.txt](https://github.com/OoliteProject/oolite/files/1046330/Latest.log.txt)

Thanks for all the help.  What I'd like to say is, I'm not concerned about this condition, but I am happy to keep working to get to the bottom of it if that would be helpful.  I only mention this because if you aren't concerned about it on your end, and am only answering to be helpful to me, then let's all just get back to playing and having fun.  On the other hand, if this is at all helpful, I'm more than happy to keep troubleshooting whenever the problem crops up.

Thanks again!

**Comment by AnotherCommander** [comment]
We are very much concerned about any anomaly that interferes with the gameplay experience. We should do our best to understand what is going on here, because whatever it is that is causing ithe issue, reinstalling the game is not considered an acceptable solution. 

The keyconfig in your AddOns/Config folder is irrelevant. A descriptions.plist might be an indication, but since there is no such file there, then we will have to look elsewhere. 

So, the issue occurred again without OXPs and without any errors in the log. That's interesting, because it probably means that the string expansion taking place when the strings for the data screen are generated is failing for some reason.

To try to track this further, I have attached below a 64-bit executable based on 412349f, which has some logging added in the F7 screen, in order to get as much information as possible about what happens when the description strings are created. Please rename or backup oolite.exe in your nightly build's oolite.app folder and drop this executable instead. Then play the game normally and as soon as the problem happens again, exit and send us the Latest.log. We'll hopefully get a hint from that.

Thanks for your time and help in investigating.

[oolite#228Test01.zip](https://github.com/OoliteProject/oolite/files/1047472/oolite.228Test01.zip)

**Comment by myxomycophyta** [comment]
OK, thanks! 

I overwrote the C:\Oolite-Trunk\oolite.app\oolite.exe file with your zipped Oolite.exe, loaded my most recent save, went straight to F7, and noted that the problem continues to recur.  

I double checked my desktop shortcut, and confirmed it's launching the trunk version with this command:
C:\Oolite-Trunk\oolite.app\oolite.exe -nosplash

I exited by left clicking on the red "X" in the upper right hand corner of the window.

In a minute I'll re-run without the -nosplash option, but first, here's the Latest.log:
[Latest.log.txt](https://github.com/OoliteProject/oolite/files/1049269/Latest.log.txt)

Now, running without the -nosplash option, the outcome appears the same as the above screenshot.  That was just a silly idea I had that didn't appear to pan out.

This time I exited with the F2/Exit command.  FWIW, here's the Latest.log from the -nosplash run:
[Latest.log2.txt](https://github.com/OoliteProject/oolite/files/1049289/Latest.log2.txt)

In both cases, Oolite confirmed the version with green characters in the upper right of the window: "Development version 1.85 0 412349f #228_01"

It's probably not relevant, but here's the save file I started with in both of the above cases:
[765.oolite-save.txt](https://github.com/OoliteProject/oolite/files/1049290/765.oolite-save.txt)

Also, here's something possibly of interest about my configuration.  In my C:\ root directory, I have two different gaming folders.  I have Oolite, and I have Oolite-Trunk.  I've been running from C:\Oolite-Trunk\oolite.app\, but I've redirected games to load and save from the C:\Oolite\oolite.app\oolite-saves folder.

All of this may not matter, just trying to think of anything unusual in my setup.  Thanks for everything! I hope this logging was more helpful.

**Comment by AnotherCommander** [comment]
First off, thanks very much for the exhaustive report and for dedicating aal this time to investigate. Really appreciated.

Following this last post though, we now have confirmation that something is off in your Oolite setup. Certain things just don't look right.  Let's take them one by one:
- The Latest.log files. I noticed something a bit unusual yesterday when I saw the Latest.log you sent had a date of 31st May. I thought it must have been due to time zone difference and did not pay too much attention to it. However, looking at the last two trunk logs, I can't help but notice two things: a) They are identical in content (and they are identical to the Latest.log sent previously too) and b) they are dated 31st May, all three of them. They cannot possibly be logs from the runs you describe in your last post. What is the location where you took these logs from?
- The Oolite executable version reported in the logs is NOT the one I sent you. You have metnioned also that the version appearing on the trunk on-screen watermark reads 1.85 0 412349f #228_01, but if you see the one reported in the log files, it belongs to the standard trunk version.

So, looks like something is off there. I would recommend that you try to locate the log files from your actual last run (they should be reporting the 1.85 0 412349f #228_01 version on the log header too). I expect they will contain errors similar  to what we've already discussed, or at least a good hint of where to look at for the root cause of the problem..

As to why 1.84 behaves differently, it's because we did some changes to the way the F7 information is presented in trunk and that happened very recently too. But if you have mixed files from earlier trunks with a recent executable, chances are you will get this lack of system data. We'll be able to get confirmation only once we have seen the correct log files from a problem run. In case those logs cannot be located, I would suggest a re-install of trunk in a completely new, clean place, without any cross-talk between versions (although, I don't beleive the saves folder redirection to be the issue, I do it myself too just like you do) or any OXP or Config folders external to the core game.

**Comment by KonstantinosSykas** [comment]
If the issue persists with the fresh clean installation with no redirects (as AnotherCommander suggested), please, exit Oolite, 
ensure that no other Oolite instance is running (`Ctrl+Shift+Esc` will help you check that) , 
delete the file `C:\[Oolite-Trunk root folder]\oolite.app\GNUstep\Defaults\.GNUstepDefaults` and
re-execute Oolite from the Oolite-Trunk folder. 
Play Oolite in the original sized window (i.e. do not resize or go into fullscreen mode). 
Is the issue still there?

**Comment by myxomycophyta** [comment]
** don't spend much time reading this, as it's incomplete, inconclusive, and in the middle of testing that requires a computer restart **

Hi.  First, I'd like to say, I'm really sorry to have been wasting your time by providing irrelevant log files for the past few days.  You've helped me to realize that I made a bad assumption about Oolite behavoir.  I assumed that there was no interaction among the Oolite 1.85 and 1.84 installations, since they each have their own separate directories.

Looking back at my log files, it seems that oolite-trunk-1.85.0.412349f-dev.x64.exe, which I installed in C:\Oolite-Trunk, is writing log files to C:\Oolite, which is where I installed Oolite-1.84_x64.exe.

Since 1.85 is writing logs in the 1.84 directory tree, is it possible that it's also looking at the descriptions.plist in the 1.84 directory tree?  That might explain the problem.

Then, the question might be, why is it doing this?  I started this thread by saying, 

> I loaded 822.oolite-save into Bemaera.

To redirect the Oolite 1.85 save game directory, I used F2, Load Commander, CTRL-Enter all the way up to the C:\ directory, then clicked down to the C:\Oolite\oolite.app\oolite-saves directory where my most recent 1.84 game was saved.

So, I wonder, could this have redirected other paths so that now 1.85 is inappropriately looking at 1.84 files?

Going with that hunch, I've done the following:
1) Backed up my saved games to an unrelated folder
2) Deleted both C:\Oolite and C:\Oolite-Trunk folders in their entirety.
3) Installed Oolite-1.84_x64.exe to C:\Oolite
4) Installed oolite-trunk-1.85.0.412349f-dev.x64.exe to C:\Oolite-Trunk
5) Copied oolite.exe from oolite.228Test01.zip over C:\Oolite-Trunk\oolite.app\oolite.exe
6) Copied my most recent saved game to the 1.84 directory at C:\Oolite\oolite.app\oolite-saves
7) I had forgot to back up my custom keyboard interface, so I copied it from this site to both C:\Oolite\AddOns\Config and C:\Oolite-Trunk\AddOns\Config, renaming both to remove the .txt suffix.
8) Executed C:\Oolite-Trunk\oolite.app\oolite.exe
9) Started Playing with 1.85 with the default Commander Jameson at Lave.  

Right away, my F7 shows the missing information.  This was surprising, because how can that behavoir persist after deleting both directories and reinstalling?

First, let's test my theory about 1.85 looking in 1.84 directories.   With F7 at Lave, although the yellow planetary data text is missing, I can still see the green planetary data text, which says:

> Lave is most famous for its vast rain forests and the Laveian tree grub.

So, I'm going to edit the C:\Oolite\oolite.app\Resources\Config\descriptions.plist file within the 1.84 path to change this description, but I won't touch the descriptions.plist within the 1.85 path, so when I run 1.85 there should be no effect.  Within the 1.84 path descriptions.plist, line 317, I'm changing "grub" to now be "flub".  Now I'm running 1.85 with the default Commander Jameson at Lave and hitting F7.  I expect it to say, 
> Lave is most famous for its vast rain forests and the Laveian tree flub.

No, it doesn't say that:  it had no effect on the F7 message in 1.85, so that theory is a bust.

To double check, I ran 1.84 with a new start at Lave and hit F7, and IT ALSO did NOT report the Laveian tree flub.  I'm so wrong that I need to do some exploration to improve my understanding of what's going on here.

I reopened the 1.84 C:\Oolite\oolite.app\Resources\Config\descriptions.plist and confirmed that my changes had been saved.  They were, it does say "flub" and not "grub"

Well, I now guess that it's using a different descriptions.plist somewhere else.  Searching...

Nope, can't find one. 

OK, well, sometimes Windows does strange disk caching.  I think it's time to completely uninstall both Oolites again, then restart windows this time, then reinstall both 1.84 and 1.85, then check this again.  

I'll report back soon.

**Comment by AnotherCommander** [comment]
Oolite is caching its data for performance reasons. Whenever you change a file within a resource folder, be it core Resources or OXP, you need to restart the game with the Shift key held down, to indicate that you are requesting a cache refresh.

As for the separate installations, they should indeed work completely indpendently and separately and they have been doing this for years now. I have no idea why your 1.85 install would have any interference whatsoever with the 1.84 one. Are you using symlinks in Windows?

Also, see if anything changes by starting the game not from its shortcuts, but from within oolite.app by running directly oolite.exe.

**Comment by myxomycophyta** [comment]
Using Regedit, I've found a number of bits of Oolite that I'm in the process of manually deleting from the registry.  Because I've not been a good uninstaller, this may be unrelated to your uninstaller, but I though I'd mention them (please disregard if irrelevant).

The ones I thought might be of interest (or not, because, you know, I don't know about this stuff) are the Microsoft program diagnostic entries, where something went wrong like heap leakage or other error reporting.

After this, I'll do a restart and a fresh reinstall, then get back to you with log files if the missing planet data persists.

Registry Key:
HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Shell\MuiCache\

Entries:
C:\Users\Hal\Documents\Games\Oolite\Oolite-1.80_x64.exe
C:\Users\Hal\Documents\Games\Oolite\Programs\Oolite-1.73.4-test.exe
C:\Users\Hal\Documents\Games\Oolite\Programs\Oolite-1.80_x64.exe
C:\Users\Hal\Documents\Games\Oolite\Programs\Oolite-1.84_x64.exe
C:\Users\Hal\Documents\Games\Oolite\Programs\Oolite-1.84_x86.exe
C:\Users\Hal\Documents\Games\Oolite\Programs\oolite-trunk-1.85.0.412349f-dev.x64.exe


Registry Key:
\HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\LowRegistry\Audio\PolicyConfig\PropertyStore

Entries:
Multiple quite long arbitrary identification strings terminated with one of the following:
}|\Device\HarddiskVolume2\Oolite\oolite.app\oolite.exe%...
}|\Device\HarddiskVolume2\Oolite-Trunk\oolite.app\oolite.exe%...
The remainder of the strings aren't visible, but I'd guess it would be -nospalsh.


Registry Key:
\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.oolite-save

Entry:
REG_SZ (value not set)


Registry Key:
\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths

Entries:
REG_SZ (multiple)


Registry Key:
\HKEY_CURRENT_USER\Software\Microsoft\Windows\Windows Error Reporting\Debug

Entries:
C:\Users\Hal\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppHang_oolite.exe_703bc637a5a0c0325aa9542c731bf0f38fe84c54_1fa3d651


Registry Key:
\HKEY_CURRENT_USER\Software\Microsoft\DirectInput\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Persisted

Entries:
C:\Users\Hal\Documents\Games\Oolite\Programs\Oolite-1.73.4-test.exe


Registry Key:
\HKEY_LOCAL_MACHINE\Microsoft\Software\RADAR\HeapLeakDetection\DiagnosedApplications\oolite.exe

Entries:
REG_QWORD  0x1d2d19c9d45dd16

**Comment by myxomycophyta** [comment]
I don't know that I am running symlinks, but if it's some kind of default behavior then I probably am.  If it required me to do something like install a package, then I am pretty sure that I am not.  Also, there is no such app under "uninstall programs."

Thanks for reminding me of the shift-on-start requirement.  I'll try to remember.

I'll have something useful to report in an hour or so.

**Comment by myxomycophyta** [comment]
OK, here are my boundary conditions:
I uninstalled Oolite-1.84_x64.exe.
I uninstalled oolite-trunk-1.85.0.412349f-dev.x64.exe.
I restarted the computer.
I used Regedit to remove most remaining registry entries associated with Oolite environment variables or paths.  I didn't worry about those entries, for example, that showed I had saved a MS Office or Paint file with Oolite as part of its name, or that Oolite.exe was the last program I had run, etc.
I restarted the computer.
I ran ccleaner.
I restarted the computer.
Now, with the computer allegedly clear of any oolite history, I reinstalled oolite.
I reinstalled oolite-trunk-1.85.0.412349f-dev.x64.exe into a newly created c:\Oolite folder.
I reinstalled oolite-trunk-1.85.0.412349f-dev.x64.exe into a newly created c:\Oolite-Trunk folder.
I overwrote C:\Oolite-Trunk\oolite.app\oolite.exe with the oolite.exe from oolite.228Test01.zip.
In both c:\Oolite\AddOns and c:\Oolite-Trunk\AddOns, I created a Config folder and copied my custom keyconfig.plist into it.

Why did I do all this?

Earlier, I had forgotten about the shift-key on startup to recreate the cache, and I was wondering why I had edited the 1.84 descriptions.plist file, yet it appeared to have no effect on the 1.84 planetary descriptions.  I think you've explained why that was the case, but that was what started the uninstall-reinstall saga.

Afterward, I had uninstalled all Oolites and deleted their folders, then reinstalled them, yet the 1.85 version still had the missing planet data problem.  I began to wonder if there could be some kind of Windows caching or persistence that I should try to eliminate.  So, here we are.

Next steps:  Run the 1.85 version again, and play until it no longer displays planetary data, then provide you with a Latest.log file.

So, after the clean install, I haven't run the 1.84 version at all (although I did install it).  Now I started the 1.85 version by doubleclicking C:\Oolite-Trunk\oolite.app\oolite.exe, beginning with a normal start in Lave.  F7 displays full planetary data, as it should.

I've deleted them, so there's no way of checking now, but I begin to wonder if I messed up the 1.85 shortcut?  If the shortcut was created by copying and editing the 1.84 shortcut (it probably was), then could I have updated the target correctly to C:\Oolite-Trunk\oolite.app\oolite.exe, but forgot to change the start path variable from C:\Oolite\oolite.app?  That might explain the symptoms, right?  Particularly why the log files would have been written to the 1.84 directory.

Summary:  Everything seems to be working properly.  I'll play for a bit and if it doesn't recur, we'll know it's user error.

Thanks for your help and your patience, and I'm very sorry if my own stupidity caused you to fruitlessly spend time that could have been better spent elsewhere.

**Comment by myxomycophyta** [comment]
Well, after sustained gameplay over several intervals, everything is working properly.  It's really unfortunate that a Windows shortcut error could lead to all this confusion and effort.  Although I've said it before, I'd like to thank everyone for all the assistance, and apologize for creating fruitless labor.
Regrettably aptly named, myxomycophyta
