### ISSUE TITLE
Fullscreen mode not working

### ISSUE THREAD

**Issue by KonstantinosSykas** [OoliteProject/oolite#229]
**System:** Lenovo Thinkpad X1 Yoga (Type 20FR)
**Display adapter:** Intel HD Graphics 520
**Driver:** (25/5/2016) 20.19.15.4463
**O/S:** Windows 10 Enterprise 64-bit
**Oolite:** Nightly release 27/5/2017 (commit 412349f)

**Description**
Tried fullscreen at first run of fresh new install. Nothing happened. After that, the window handling became erratic. Trying to move the window just placed it on the top left corner of the screen. Double clicking on the title bar, start flashing rapidly the Oolite window making impossible to regain focus; killed it. Restarting Oolite (w/ or w/o `Shift`) opened a borderless and ... textless (!!!) window on the top left screen corner; `Shift`+`Esc` properly exited Oolite.
Deleting `.GNUstepDefaults` and restarting Oolite, showed properly the 800x600 window. Pressing `F12` just replicated the behavior.

**Initial Analysis and work around:**
Starting Oolite in windowed mode with new commander and Normal mode, I opened the options to notice a weird resolution of 1463x823.
![oddfullscreenresolution](https://cloud.githubusercontent.com/assets/5579524/26824383/cfcb62f6-4ab9-11e7-9b6c-70a509572d7b.png)
Moving the cursor to that row and pressing the right arrow key, showed the proper 2560x1440 resolution. Now fullscreen works.

It just flashed into my mind and checked the ratios 2560/1463 and 1440/823 and they both proved to be 1.75. This led me to the following display setting (right-click on the desktop and select `Display settings`).
![displayscaling](https://cloud.githubusercontent.com/assets/5579524/26824738/3677fae0-4abb-11e7-8bca-ae4ca2aa0d4a.png)
Setting the scaling to 100% and deleting the `.GNUstepDefaults` file, resolved the issue. Oolite was reporting the correct screen resolution.

I am not in the position to download the latest drivers right now, but in the meantime, does anyone else has the same behavior?
I attach the latest log for reference.
~~Latest.log.txt~~
(Correct log attached, demonstrating ERROR)
[Latest.log.txt](https://github.com/OoliteProject/oolite/files/1066255/Latest.log.txt)

**Comment by AnotherCommander** [comment]
Can you please run the attached minimal scenario program at various DPI settings and check whether the correct DPI is being reported? IF it is, we could maybe adjust the nominal desktop native resolution to its 
correct value during startup.
[dpiaw.zip](https://github.com/OoliteProject/oolite/files/1054739/dpiaw.zip)

**Comment by KonstantinosSykas** [comment]
I didn't exactly get the meaning of 
>...various DPI settings...

What I did, is tried various resolutions and scales 
2560 x 1440 (100%, 150%, 175%)
1600 x 900 (100%, 125%)
1440 x 900 (100%, 125%)
and they all reported
>C:\\>dpiaw.exe
>setProcessDPIAware() loaded.
>DPI detected: 168.000000
>
>C:\\>

Please, note, that I could only run this from within a command line prompt.

**Comment by KonstantinosSykas** [comment]
The following getScalingFactor() function, interesting you should find:
https://stackoverflow.com/questions/5977445/how-to-get-windows-display-settings#21450169

**Comment by AnotherCommander** [comment]
Great find. Pointed me to the correct parameters to be looking at. Lets try again. Please repeat the test with the attached exe. Command line, as before, run it in various settings just like you did earlier.
[dpiaw02.zip](https://github.com/OoliteProject/oolite/files/1055198/dpiaw02.zip)

**Comment by KonstantinosSykas** [comment]
I think it's a bullseye. 
However, let's see how it will behave in the code. I suggest to only use it to get the fullscreen resolution only and not for the rest of the window operations. I can experiment with multiple monitors too.
I can try various code versions before actually going into the nightly.

**Test results**
>`1440 x 900 @100%`
>C:\\>dpiaw02.exe
>Screen Scaling Factor detected: 1.000000

>`1440 x 900 @150%`
>C:\\>dpiaw02.exe
>Screen Scaling Factor detected: 1.500000

>`1600 x 900 @100%`
>C:\\>dpiaw02.exe
>Screen Scaling Factor detected: 1.000000

>`1600 x 900 @125%`
>C:\\>dpiaw02.exe
>Screen Scaling Factor detected: 1.250000

>`2560 x 1440 @100%`
>C:\\>dpiaw02.exe
>Screen Scaling Factor detected: 1.000000

>`2560 x 1440 @125%`
>C:\\>dpiaw02.exe
>Screen Scaling Factor detected: 1.250000

>`2560 x 1440 @150%`
>C:\\>dpiaw02.exe
>Screen Scaling Factor detected: 1.500000

**Comment by AnotherCommander** [comment]
How does this patch work for you? Can you please apply, test and let us know?
[229_01.diff.txt](https://github.com/OoliteProject/oolite/files/1055483/229_01.diff.txt)

**Comment by KonstantinosSykas** [comment]
With a minor change the patch works.  :tada:

To specify floating point math, replace
`src/SDL/MyOpenGLView.m (Line 803): 	return (float)(physicalScreenHeight / logicalScreenHeight);`
by
`src/SDL/MyOpenGLView.m (Line 803): 	return (float)physicalScreenHeight / logicalScreenHeight;`
else, you just cast to `float` the integer division result.

I attach the successful test log.
[Latest.log.txt](https://github.com/OoliteProject/oolite/files/1057513/Latest.log.txt)

Tonight I should be able to test with dual monitor.

**Comment by AnotherCommander** [comment]
Great. Just to have a more complete log, before you test-run it next time change inside logcontrol.plist the line `display.mode.list = no;` to `display.mode.list = yes;`, so that we will have in the log the full list of resolutions recognized.

**Comment by AnotherCommander** [comment]
Attached are two new patches. 229_02 is just a better way of doing exactly the same as 229_01. 229_03 is a very small one that just tries to use GetDeviceCaps instead of GetSystemMetrics to acquire the physical dimensions of the dekstop during startup. If this works, then we might be able to get away with having to deal with the screen scaling factor, although I am afraid we might still need to account for it on the secondary monitor(s).

Both patches are against latest trunk (2ba6cf6)

Let's hope the tests bring us some good news.
[229_02.diff.txt](https://github.com/OoliteProject/oolite/files/1061834/229_02.diff.txt)
[229_03.diff.txt](https://github.com/OoliteProject/oolite/files/1061838/229_03.diff.txt)

**Comment by AnotherCommander** [comment]
Just wanted to add that this issue seems very closely related to the (now closed) #226.

**Comment by AnotherCommander** [comment]
I think I has solution.

After so many Patches of Agony, it seems that all we really had to do was declare our app as DPI-aware, so that Windows automatic DPI virtualization would not kick-in. Here is what I believe is our solution to the problem:
```
diff --git a/src/SDL/main.m b/src/SDL/main.m
index 2fcf01b..28c28a7 100644
--- a/src/SDL/main.m
+++ b/src/SDL/main.m
@@ -80,6 +80,15 @@ int main(int argc, char *argv[])
 		numbers don't behave strangely.
 	*/
 	setlocale(LC_ALL, "C");
+	
+	/*
+		Declare the application as DPI-aware, so that Windows Vista and later
+		versions' automatic DPI virtualization does not kick-in. Attempt to
+		load the SetProcessDPIAware Winapi funtion and execute it if available.
+	*/
+	static BOOL(WINAPI* setProcessDPIAware)() = NULL;
+	setProcessDPIAware = (BOOL(WINAPI*)())(void*)GetProcAddress(GetModuleHandle("user32.dll"), "SetProcessDPIAware");
+	if (setProcessDPIAware)  setProcessDPIAware();
 #endif
 
 	// Need this because we're not using the default run loop's autorelease
```
Please test and kindly give me some good news :-)

**Comment by KonstantinosSykas** [comment]
It is indeed a duplicate for #226 ; sorry I missed that. :flushed: 

You can't imagine the side effects I was ready to report (e.g. stretched window content upon fullscreen oolite restart, Oolite title out of the window limits on the rotating cobra screen, etc.) :relieved: 

I have already successfully tested the 412349f nightly executable unpatched, setting the relevant executable property as per attached screenshot.
<img width="270" alt="dpiawareness" src="https://user-images.githubusercontent.com/5579524/27024891-21d043ae-4f61-11e7-9fe2-52a2436b02ac.png">

I will revert more feedback on the patch you suggest, unchecking the executable compatibility property, later tonight. :crossed_fingers:

**Comment by KonstantinosSykas** [comment]
:
Laptop 2560x1440 (scale 150%). Second monitor 1920x1080
Deleted .GNUstepDefaults. Start Oolite. Move Oolite window to the secondary monitor.
Maximize Oolite window. Exit Oolite. 
.GNUstepDefaults indicates window size 2880x1526. :disappointed: 
It actually stores the window size considering the scale of the primary display. 
The height is not exactly 1080x1.5 due to the windows taskbar size. 
[GNUstepDefaults.txt](https://github.com/OoliteProject/oolite/files/1069857/GNUstepDefaults.txt)
[Latest.log.txt](https://github.com/OoliteProject/oolite/files/1069859/Latest.log.txt)

**Comment by AnotherCommander** [comment]
Facepalm
Sigh
Wipes tears
...
OK, one more time. Let's try this patch (sequel 8 of the saga). Windows 8.1 and higher have the "per monitor" dpi awareness capability, so let's use that.  The attached patch will try to load the funtion SetProcessDPIAwareness from the shcore.dll, available only on later Windows versions. If it succeeds, it will set dpi awareness to be per monitor and this should hoipefully resolve the issue. If the function fails to load, then we will go ahead and try to load the older SetProcessDPIAware..

There are a couple of debug messages there. On Windows 10 you should see at the top of the log:
```
[unclassified.MyOpenGLView]: SetProcessDPIAwareness: run
[unclassified.MyOpenGLView]: SetProcessDPIAware: not run
```
This will confirm that the correct API function has been loaded and executed.

I am about to give up if this doesn't work. So it'd better work.
[229_08_feb6270.diff.txt](https://github.com/OoliteProject/oolite/files/1070822/229_08_feb6270.diff.txt)

**Comment by KonstantinosSykas** [comment]
It didn't. :disappointed: 
```
14:47:43.124 [unclassified.MyOpenGLView]: SetProcessDPIAwareness: not run
14:47:43.124 [unclassified.MyOpenGLView]: SetProcessDPIAware: run
```

**Comment by AnotherCommander** [comment]
Double Facepalm...

That was just me being me... typo in the WinAPI function call...
It is not SetProcessDPIAwareness, it is SetProcessDpiAwareness. Sorry about that. Just correct this mistake and it should work.

**Comment by KonstantinosSykas** [comment]
It does, as expected! :ok_hand: 
```
17:02:29.688 [unclassified.MyOpenGLView]: SetProcessDpiAwareness: run
17:02:29.688 [unclassified.MyOpenGLView]: GetProcessDpiAwareness: 2
17:02:29.688 [unclassified.MyOpenGLView]: SetProcessDPIAware: not run
```
The extra line, is from a check I performed, using the `GetProcessDpiAwareness()` to compare between 
1. setting the awareness from the executable file "Compatibility" property to "Disable display scaling on high DPI settings"and 
2. setting the awareness using `SetProcessDpiAwareness()`.

Both methods return the value 2, that is `PROCESS_PER_MONITOR_DPI_AWARE`. 
Waiting for the final patch to actually verify with a second display. :relieved:

**Comment by KonstantinosSykas** [comment]
Patch `229_09_32cbe37.diff.txt` does it! Well done a_c! :sunglasses:
