### ISSUE TITLE
Density in shipdata.plist having no effect.

### ISSUE THREAD

**Issue by DTHP** [OoliteProject/oolite#231]
setting the density to any value have no effect on calculated mass of the ship.

This is significant for large but empty objects. Imagine a bulk cargo container or pirate-interdiction ships or in my case a Babylon 5 jumpgate that makes the AI act funny because of its huge mass at the witchpoint.

**Comment by AnotherCommander** [comment]
In a clean, no-OXPs installation, I try the following:
1. Launch debug console and Oolite.
2. Start new commander, launch at Lave.
3. Immediately target the buoy and execute on the console `PS.target.mass`. The console responds:
```
> PS.target.mass
383595.9375
```
4. Switch to rear view, target station and execute `PS.target.mass` again. Response:
```
> PS.target.mass
515483904
```
5. Exit the game, go to shipdata.plist and add the following lines in the template definitions of nav buoy and coriolis respectively:
`density = 0.5`
`density = 0.1`
6. Shift-start, new commander and launch from Lave.
7. Immediately target buoy, then execute `PS.target.mass`. Response:
```
> PS.target.mass
191797.96875
```
8. Switch to rear view, target station, execute again `PS.target.mass`. Response:
```
> PS.target.mass
309698080
```
Apart from the fact that the station mass is not one tenth of the original (explained by the existense of subentities that were not edited for density), what exactly doesn't work?

**Comment by DTHP** [comment]
I'm Sorry. I have found the same results as you today. I swear I didn't yesterday(i tested some 10 times). So this is bogus. Can't figure what have been causing this irratic behavior on my side. Jumpgate with 1.0 and 0.1 in density now gives correct mass readings. i have allways flush set to on in gnustep default. :/.
