### ISSUE TITLE
background color of `message_gui` visible while docked

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#236]
If you add a background colour value to the `message_gui`, this background is also visible while docked in all screens (e.g. market screen, save screen, equipment screen, etc.). The same is not true for the `comm_log_gui` as it automatically hides after while. Would it be perhaps possible to implement one of the following?

- automatically hide `message_gui` while docked
- add the parameter `viewscreen_only` to the `message_gui`, so that `viewscreen_only = 1;` can be used

**Comment by AnotherCommander** [comment]
Please try out commit 4fd9403. It should hopefully address this issue in a satisfactory way. The message gui background now follows the messages displayed and fades out with them. If the permanent key is set for message_gui in hud.plist, then the message gui background is displayed at all times, even when docked.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander Many, many thanks, as soon as there is a nightly build ready I will check it out.

**Comment by gilbertohasnofb** [comment]
Just tested the nightly build, it works perfectly -- thanks a lot. But if one would feel like tweaking a bit the effect, it seems to me that the `message_gui` fades a little bit too fast, perhaps it could stay 1 whole second or so in full brightness before starting to fade out. But that's of course a very minor detail and this issue is completely solved, so I suppose we should close this.

(about which I have a quick question: when an issue I opened is solved, should I close it myself or is it always better to let one of your in the development team judge and close it?)

**Comment by AnotherCommander** [comment]
If you are happy with the solution provided, you can close it youtself too. IF we feel that it needs further discussion we can always re-open. Same goes for you if we close an issue that you don't feel happy about; you can re-open it and request further investigation (preferrably with justification why the current solution is not deemed satisfactory). For this one, I am going to save you the trouble and close it while posting this comment.

Thanks for testing it out.

**Comment by gilbertohasnofb** [comment]
All clear, many thanks.

**Comment by gilbertohasnofb** [comment]
As of the most recent nightly, there is a bug that was likely caused by the implementation of the solution for this issue. The function `player.consoleMessage()` now outputs a string to the `message_gui` but it does not automatically open the gui. On the other hand, switching primable equipments or toggling weapons online/offline does bring the gui, which then does show a previously recent string output by `player.consoleMessage()`.

**Comment by AnotherCommander** [comment]
There have been some other issues, as reported also in the forum (hyperspace countdown messages, but game over messages as well).. I have made some refactoring and further fixes to cover all cases (hopefully). Please test the upcoming nightly and let us know if there are still problems.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander I just tested it but the function `player.consoleMessage()` is still not automatically showing the `message_gui`. I am adding the function `player.consoleMessage()` to the js script that controls a HUD I am working on, perhaps I am doing something wrong? But these messages are actually being output to the `message_gui`, the issue is that the gui keeps hidden when those message events happen.

**Comment by AnotherCommander** [comment]
Yes, confirmed. I am doing yet another refactor of the implementation and I think this time it works (at least the Xenon HUD behaves nicely now). will copy the patch file here in case you want to test on Linux and will publish a Windows test binary on the forum once ready.

**Comment by phkb** [comment]
What I notice with the latest build is that the background of the message_gui isn't fading out any more, like it was doing in earlier patches. In Xenon HUD, the hi-contrast demonstrates the issue, as the message_gui alpha is set to 1.

**Comment by AnotherCommander** [comment]
@phkb Actually, this was deliberate. I am experimenting with different functionality types. To bring back the previous behaviour, comment out the line in GuiDisplayGen.m below the comment that reads: "// comment line below to make a gui that fades out with its messages"

Not sure which of the two behaviours should be the default. If it is expected that the message background will be fading together with the message, then we can easily do that. In my personal build I am currently testing an "automatic" message gui flag, that will allow control on this exact point.

**Comment by phkb** [comment]
Ah! Thanks, a_c.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander 

> I will copy the patch file here in case you want to test on Linux and will publish a Windows test binary on the forum once ready.

Hmm, I am not familiar with compiling Oolite. I will see if I manage to do it soon.

> Not sure which of the two behaviours should be the default. If it is expected that the message background will be fading together with the message, then we can easily do that. 

I think the fading behaviour was very nice, for me the only issue was the messages from `player.consoleMessage()` not forcing the GUI to pop up. Were there other issues reported concerning it?

**Comment by AnotherCommander** [comment]
@gilbertohasnofb  User gizmo on the forums has reported that the test exe worked fine regarding the Xenon HUD messages, which were basically player.consoleMessage calls. I have been able to confirm that the Xenon HUD works fine here and generates correctly its console messages using the latest build.

You can try today's nightly yourself to test, it has been already published in the nighlties repository. Oh, and I will revert the default background behaviour back to fully automatic. and use a hud key to alter it if needed.

**Comment by gilbertohasnofb** [comment]
> You can try today's nightly yourself to test, it has been already published in the nighlties repository.

I actually already did test it, but it seemed to me that the behaviour has been reverted and that `message_gui` is now constantly visible, did I understand something wrong?

**Comment by AnotherCommander** [comment]
No, what you see now is not what I call fully automatic. It was just a different way of functioning. With fully automatic I mean that it pops up only when there is a message and disappears together with the message. In the next nightly, this fully automatic way will be the default and the "persistent way" you see now will be selectable via a hud.plist key.

**Comment by gilbertohasnofb** [comment]
That's all clear now! Ok, so I will be looking forward to the next nightly and then I will report here is the fully automatic behaviour is working well on my side. Many thanks for all the trouble implementing this!

**Comment by gilbertohasnofb** [comment]
@AnotherCommander I just tested the new nightly and the behaviour is absolutely perfect now, the automatic hiding works like a charm and `player.consoleMessage()` now unhides it as well. Thank you so much for implementing this!
