### ISSUE TITLE
Mouse control behaviour

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#237]
Currently when mouse control is active, any movements to the mouse cursor position will result in a simulated joystick input to the ship. This is of course the expected behaviour while controlling the ship, but moving the mouse while docked result in input changes, which are then immediate output when the ship launches. The same is true when accessing the galactic chart in flight, if one uses the mouse to zoom, drag and plan a route, as soon as F1 is hit the ship will be spinning. Perhaps a better behaviour would be to have the mouse control disabled in those two situations.

**Comment by AnotherCommander** [comment]
Good catch! This should be fixed with commit 1b95d31

**Comment by gilbertohasnofb** [comment]
Great, and that was fast! If this commit makes into the next nightly I will test this tomorrow together with the new message colours commit.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander that commit solves the issue completely when it comes to using the mouse while docked, but it does not address the issue of using the mouse in the galactic chart while in flight. The interesting thing is, when you are in the galactic chart in flight and using the mouse to plot a path, you can see from the scanner that the mouse is NOT controlling the ship (i.e. the ship remains in the same course), but as soon as you leave that screen, the last mouse position in the chart is then set as the new joystick input and the ship can start to spin chaotically depending on where your cursor last was. Do you think it would be possible to also reset the mouse after using the galactic chart or any of the other F<number> screens mid-flight?

**Comment by AnotherCommander** [comment]
Damn I didn't think of checking in-flight. Will take a look at it soon.

**Comment by AnotherCommander** [comment]
We are now resetting the mouse also when entering one of the external view screens from a GUI screen. This should hopefully cover also the in-flight cases.

**Comment by gilbertohasnofb** [comment]
Just tested the newest nightly, everything is perfect now, thanks a lot.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander I am sorry for reopening this, but I spot one more problem with this issue. In the external view, once can toggle the Caps Lock key to activate the new camera system and use the mouse to click and drag the camera. Once the Caps Lock key is released, the ship will use the last mouse position as input and move chaotically as described before. Perhaps it would be good to reset the mouse movement after the Caps Lock key is toggled off if Mouse Control is ON.

(on a side note, I noticed that clicking and dragging with the mouse and with Caps Lock ON to change the camera has a limit range  of angles, you cannot do a 360 around the ship, while using the keyboard keys that can be accomplished. Is this also a bug or am I misunderstanding how the new camera system works?)

**Comment by AnotherCommander** [comment]
Please try commit 41841ed. Let's hope for the best.

As for the side note, yes it is "a bit" of a bug. You can rotate the ship fully but there is a block on the mouse. Imagine a mouse cursor at the center of the screen. You start rotating the view camera by moving it to the left. The mouse cursor moves to the left and the camera rotates with it. When you reach the border of the window, the cursor stops and with it the camera movement. That's why it feels like a limited angle of rotation. You can still right click and re-center the mouse, then continue the rotation, but I think this is a bug for another time.

**Comment by gilbertohasnofb** [comment]
> Please try commit 41841ed. Let's hope for the best.

This commit solves it, thanks a lot.

> As for the side note, yes it is "a bit" of a bug. You can rotate the ship fully but there is a block on the mouse. 

I see, I realized that this block exist in other screens (my mouse cursor does reach the corners in some of the F<number> screens).

> You can still right click and re-center the mouse, then continue the rotation, but I think this is a bug for another time.

You are right, this works. Perhaps the mouse could be centralized when the left button is released, so that you can click and drag, click and drag, click and drag. But anyway, this is not a big deal, thanks again.
