### ISSUE TITLE
In the F7 screen, planet shows wrong atmosphere colour

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#239]
Small report: In the F7 screen (Data on <planet name>), there is a rotating image of the destination planet. The issue is that the atmosphere of the planet is shown with the colour of the _current_ star, not of that system's star.

**Comment by AnotherCommander** [comment]
Hopefully fixed with commit 1c532a4. Please test.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander Thanks for the commit. The colour issue is solved, but I discovered a very minor bug. The atmosphere look on the F7 screen depends on the _current_ distance of the ship to the planet. So for instance, this is how Quedle looks like when I am very close to it:

![screenshot from 2017-07-10 12 56 41](https://user-images.githubusercontent.com/5700795/28015341-b7072356-656f-11e7-8f81-735efa75dc43.png)

And here is how it looks if I go far away:

![screenshot from 2017-07-10 12 57 11](https://user-images.githubusercontent.com/5700795/28015342-b70e1a44-656f-11e7-90c3-a69b76ab6291.png)

The distance to the current planet also affects the look of all other planets on the F7 screen (e.g., in my case above when I was far away from Quedle all other planets in the F7 menu were displayed with a faint atmosphere).

**Comment by AnotherCommander** [comment]
I was expecting that. The distance issue was present almost from the beginning of the atmosphere shader implementation. Well, at least the color part seems sorted now.

**Comment by gilbertohasnofb** [comment]
The colour issue was much more noticeable, this is absolutely a minor issue. I just pointed out because it came to my attention, but please feel free to close this.

**Comment by AnotherCommander** [comment]
Closing since the original subject of the issue has been resolved. A new issue can be created to address the disappearing-with-distance F7 atmosphere, if deemed necessary, otherwise it goes in as a known issue for now.
