### ISSUE TITLE
Feature request: override target color

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#241]
Here is another feature request which would be really nice for HUD creators: to be able to override the colour of the targets. These have only two options as far as I can tell, either green or red (depending on the alert), and it would be nice to have two properties in the hud plist file to override each of those separately. If this is doable, would it be possible to include the following items: the square around the current target together with the name and distance of the target (which is shown around the square) as well as the small arrow showing where the target is (located around the crosshair)?

**Comment by AnotherCommander** [comment]
This feature request should be addressed by commit bdb02b.

Three new color keys can be entered now in the "drawTargetReticle:"; dials section of hud.plist. These are:
target_rgba, target_sensitive_rgba and wormhole_rgba. Default values for them are green, red and cyan respectively.

There are also three new JSPlayerShip properties, so scripts can change those colors too. The properties are read/write and they are player.ship.reticleColorTarget, player.ship.reticleColorTargetSensitive and player.ship.reticleColorWormhole.

Please advise if any issues are encountered.

**Comment by gilbertohasnofb** [comment]
Great, thank you so much for implementing this (and all the other thousand requests and bug reports I've made). I will test this tomorrow with the next nightly and let you know how it goes.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander I just tested it and it looks fantastic, very nice feature for HUD developers! But I did find a small issue which you perhaps would be interested in taking a look at. Do you know that little wedge that is around the reticle and which always points to the current target if the target is out of sight? So, the tip of the wedge is inheriting the colour from the reticle, but the other still has a green tint to it. See:

![oolite-003](https://user-images.githubusercontent.com/5700795/28267428-4ecf8e50-6afa-11e7-9525-c482884f3d6f.png)

**Comment by AnotherCommander** [comment]
I swear yesterday the colors looked fine :-)

OK, this looks like an easy fix. Remedial action commit coming up in  a few minutes. Will update this message with the tag once it's in.

**Comment by gilbertohasnofb** [comment]
> I swear yesterday the colors looked fine :-)

Hehe, this happens to me all the time :smile: Thanks for the quick fix, I will test it with tomorrow's nightly and then close this issue. I _really_ appreciate it.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander the new nightly fixes the issue indeed, it is looking great now!

**Comment by shubh10** [comment]
Try this HUD library for iOS in swift https://github.com/shubh10/JustHUD
