### ISSUE TITLE
System.infoForSystem(x, x).techlevel vs techLevel

### ISSUE THREAD

**Issue by DTHP** [OoliteProject/oolite#242]
seems to be a typo.

System.infoForSystem(x, x).techlevel works, but not
System.infoForSystem(x, x).techLevel that you would expect to be correct.

**Comment by phkb** [comment]
If it's a typo, it's one that's been in the game for a long time, and fixing it would likely break a number of OXP's which depend on one phrasing or the other, I think. 

For reference, `System.infoForSystem(x, x).techlevel` has lowercase, and `system.techLevel` has camelCase.

**Comment by AnotherCommander** [comment]
Indeed. I don't think we can afford to fix this one. Issue will be closed shortly if there are no other comments.

**Comment by DTHP** [comment]
Maybe update the wiki accordingly ?

**Comment by AnotherCommander** [comment]
Wiki updated: http://wiki.alioth.net/index.php/Oolite_JavaScript_Reference:_System#infoForSystem
Closing issue.
