### ISSUE TITLE
Keyconfig.plist not reloaded when using in-game extension manager

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#248]
I have written and uploaded an OXZ to the in-game extension manager called Dangerous Keyconfig, which is a keyboard layout replacement. After installing it via the in-game manager and returning to the main menu (i.e. applying the modifications), the new keyconfig.plist is _not_ loaded unlike all other OXZs. The only way to load it is to restart Oolite holding down the Shift key.

**Comment by notrightaway** [comment]
I recently reinstalled on a Mac, and I noticed that changing keyconfig.plist requires a shift-restart - not just a restart - so this isn't an OXP-specific issue. Is there a way for an OXP to mark this part of the cache (or even the whole cache) as stale?

If there is not, I think the right answer would be to add this feature and then update the OXP to use the new feature.

**Comment by gilbertohasnofb** [comment]
@notrightaway I think that simply changing a plist file will always require a restart with shift key pressed down, as Oolite doesn't know that those files are modified and that the cache should be rebuilt. The reason I opened this issue is that my OXP is available via the in-game extension manager, which should rebuild the cache after any changes (when going back to the main menu). So it seems that the rebuild of the cache extension manager is not the same as a shift restart, and some things do not get rebuilt.

**Comment by gilbertohasnofb** [comment]
Sorry for bumping this one but would the fix for this be too difficult? First this is a matter of consistency, since all other plists other than the keyboard shortcuts seem to be loaded automatically when overwritten by an OXP. Secondly it makes the installation of my mentioned expansion much more difficult since a lot of players don't know about the Shift+start command and only load expansions via the in-game manager. Thank you so much!

**Comment by AnotherCommander** [comment]
I think it's fixed, but it needs testing to be absolutely sure I haven't broken it somewhere else. Please have a go at the f692406 nightly when it's out and let me know.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander Thank you so much, I will test this as soon as I can. By the way, I noticed that the 64-bit Linux nightly build seems to have failed to compile.

**Comment by AnotherCommander** [comment]
Can you please elaborate? Can you give me a sequence of actions that make the problem occur? I am not sure what change you refer to here.

**Comment by gilbertohasnofb** [comment]
Here is how to reproduce it:

1) start on a clean install without Dangerous Keyconfig OXP being stalled
2) go to the expansion manager and install Dangerous Keyconfig OXP
3) apply changes and go to menu
3) start a game/load a game
4) launch the ship. You will see that Dangerous Keyconfig OXP is not taking effect (e.g. default yaw is set to `,` and `.` while Dangerous Keyconfig OXP set yaw to `a` and `d`)
5) exit Oolite
6) re-open Oolite (without holding Shift)
7) start/load a game
8) Dangerous Keyconfig OXP will now be in effect

If at this point you remove Dangerous Keyconfig OXP, the same thing will happen: the default controls will only be in effect after you quit and re-open Oolite.

**Comment by AnotherCommander** [comment]
Nope. That's not what I see here. With the above instructions and the latest nightly I get the key configuration changes applied exactly as expected.

**Comment by gilbertohasnofb** [comment]
@AnotherCommander My apologies, I had made a mistake and I had two different installations of Oolite on my system (one on my home folder, another on my system) and my shortcut was still pointing to the older one. I have removed the older installation and re-tested it, this issue is definitely solved. Many thanks for implementing this, I really appreciate it!
