### ISSUE TITLE
Small cleanup for oolite-default-atmosphere.fragment

### ISSUE THREAD

**Issue by CmdrSvengali** [OoliteProject/oolite#254]
Let's start slowly with some questions...

1. The shader uses quite a few preprocessor directives (`#if, #ifdef, #ifndef`). When logging I can only see two of them in use (`IS_OOLITE, OOSTD_HARSH_MISTRESS`). So I guess we can remove the other directives plus code inside? Maybe I'm overlooking something...

2. If not, `texCoords` and `diffuseMapSample` should be declared somewhere. I guess 1. and 2. are just partly there, because a) it's a c&p thing from the main planet shader and b) to allow easier handling in the third party tool for the author.

3. `vec3 coords = normalize(vCoords);` can be removed. It's not used anywhere. I know that the compiler does this on its own, but hey.

4. If all of them is done we can also change the vertex shader. Neither `vCoords` nor `vTexCoords`
 are used in the fragment shader and the varyings can be removed in both shaders.

5. Lets also get rid of the branching in the last part of the shader. It may not have any noticeable effect on overall performance, but even if it frees only some slots it's not a bad thing. Just as sidenote: NVidias compilers seem to be better in sorting it out. So NV cards may not have any branching at all and it is likely to be just three or four instructions less.

Anyway, it could look like:

```
float atmDistance = length(atmPosition.xyz);
float minDistance = atmRadius + 3500.0;
float fadeDist = atmRadius * 12.0;
float fadeRate = 140000.0;
float fadeStart = fadeDist - fadeRate;
float quant = ( atmDistance > fadeStart ? ( fadeRate - (atmDistance - fadeStart) ) / fadeRate : ( atmDistance < (minDistance + 2000.0 ) ? ( atmDistance - minDistance ) / 2000.0 : 1.0) );
float dp = abs(dot(normalize(vEyeVector), vec3(0.0,0.0,1.0)));
float gta = step(minDistance, atmDistance) * max(sign(fadeDist - atmDistance), 0.0);
float newOpacity = (dp > 0.16) ? min(1.0, pow(0.16 / dp, 2.0)) : pow(dp / 0.16, 5.0);
newOpacity *= gta * quant;
```

GPU Shader Analyzer gives for the oldest profile (Radeon HD 2400), which is explicitely choosen to see the differences more easily. The values are current shader vs new code.

ALU: 29 / 15
Min Cycles: 13.00 / 15.00
Max Cycles: 29.00 / 15.00
Avg Cycles: 19.45 / 15.00
Throughput: 0.21 / 0.27
INT: 2 / 2
CF: 9 / 2

Funny: The bottleneck on the HD 5870 is now the exports instead. Not so bad .-)

An example:
[oolite-default-atmosphere.zip](https://github.com/OoliteProject/oolite/files/1201745/oolite-default-atmosphere.zip)

**Comment by AnotherCommander** [comment]
A quick test of the modified fragment shader shows all OK here on the Nvidia 9600GTM. If this could be tested and confirmed working also on the ATI range of cards, I think we can go ahead and use it. Thanks @CmdrSvengali .

**Comment by gilbertohasnofb** [comment]
> If this could be tested and confirmed working also on the ATI range of cards

**Comment by gilbertohasnofb** [comment]
I just tested this on my ATI HD 7730M and everything seems to be working and it should.

**Comment by AnotherCommander** [comment]
Thanks for testing. New shader committed to trunk.
