### ISSUE TITLE
I know this isn't the right place, but…

### ISSUE THREAD

**Issue by Fleurghber** [OoliteProject/oolite#268]
Following AnotherCommander's recommendation, I attempted to sign up for the forums.

That was over a week ago, and I have heard nothing since then.

Is my application being held in a docking queue, or has it fallen down the back of a wormhole?

**Comment by AnotherCommander** [comment]
Have you checked your inbox's spam folder? Maybe there is an automatic response there?

You should have received a confirmation of account creation,, but any first post from a new account must go through moderator approval and after that you can post normally. I have not seen anything from a new account recently. If you would like to investigate further, please send an email with your username and any information you may have received from the forum to another_commander at oolite dot org and  I will check with the forum administrators and let you know.

**Comment by AnotherCommander** [comment]
@Fleurghber I see you are now active on the forum. I believe this issue can be closed.
