### ISSUE TITLE
fast activation of primable equipment is not changeable

### ISSUE THREAD

**Issue by nobswolf** [OoliteProject/oolite#280]
When docked and in the Dockside Services I choose "Primable Equipment". The list "defensive" is presented. I see my cloaking device in green and marked as "selected". the others are yellow.
When hitting UP and DOWN keys I get typing noises as sound effect, but nothing happens in the list.
When I hit ENTER, i am back in Dockside Services (and not in the "attack" list)

I run the newest trunk-version on Linux.

**Comment by nobswolf** [comment]
I guess it is a question of the number of primable equipment. First I thought it is because of the not-managed railgun. I removed it and it worked again. But is doesn't matter which one I do remove. It works with 21 items. When I add another one the fast activation selector is broken.

**Comment by AnotherCommander** [comment]
Can you please post the complete Latest.log after a failure to switch primable equipment with more than 21 items? Can't check the source right now, but I suspect an array out of bounds error, which may also be triggering exception messages in the log.

**Comment by nobswolf** [comment]
Sure. First I was in the menu with 19 items. Everything worked. Then I bought some primeable equipment. Then the menu behaved like described above.
And you are right. There is an exception at the end of the log about some range errors.
[Latest.log.gz](https://github.com/OoliteProject/oolite/files/1545638/Latest.log.gz)

**Comment by AnotherCommander** [comment]
Bug confirmed. We seem to have a case of more primable equipment items present than UI slots available for display. The fix would most likely require us to handle More and Back selections in mission screens.

**Comment by AnotherCommander** [comment]
Fixed with commit e486175.
