### ISSUE TITLE
annoying humming sound at stations

### ISSUE THREAD

**Issue by nobswolf** [OoliteProject/oolite#283]
Sometimes while docking or after leaving a station a humming sound is played continuously. 

I found one way to reproduce:

Ask for docking clearance at a Super Hub (Oresmaa, G6), then ask for docking clearance at the main station and dock there. Then leave the station.

The sound stops, when you ask for clearance at the Super Hub again.

[Latest.log](https://github.com/OoliteProject/oolite/files/1565727/Latest.log)

**Comment by AnotherCommander** [comment]
Does this happen without any OXPs installed?

**Comment by AnotherCommander** [comment]
No response received in more than a month. I suspect this is OXP related since I cannot reproduce within the standard game. Unless there is a response in the next few days, this issue will be closed.

**Comment by nobswolf** [comment]
Sorry for the delay. I had not the time to debug this in depth. But so far I think it only happens on planets with super-hubs. So I guess it is related to that OXP.
