### ISSUE TITLE
Visual glitching above text in menus

### ISSUE THREAD

**Issue by Fixer-007** [OoliteProject/oolite#285]
After update I've noticed some strange visual blinking-glitching above text when using keyboard, it appears in certain places and corrupts some letters, changes randomly. Activating some items with mouse stops the blinking. o_O
Oolite 1.86 (also on 1.84, 1.82, and probably older), Windows 7 sp1 (classic theme), ATI X800GTO OpenGL 2.1 card (yeah it is, probably the reason of this bug)
[Latest.log](https://github.com/OoliteProject/oolite/files/1580882/Latest.log)
![lel3](https://user-images.githubusercontent.com/16494741/34277993-ca2331d8-e6b0-11e7-9a14-d9a1efb1ea35.gif)
Gif step by step change difference shows the problem:
![default](https://user-images.githubusercontent.com/16494741/34278579-621bfd8c-e6b4-11e7-8af6-876a50a6a9f2.png)
![default](https://user-images.githubusercontent.com/16494741/34278756-7f31d0bc-e6b5-11e7-8cd4-eb57c22e66dd.png)
More examples:
![lel2](https://user-images.githubusercontent.com/16494741/34277923-7cddfa8e-e6b0-11e7-89e8-df72c7aaa995.gif)
![lel](https://user-images.githubusercontent.com/16494741/34277772-e46e7d28-e6af-11e7-9749-0b01d8027b1c.gif)
![kek](https://user-images.githubusercontent.com/16494741/34278504-e159ded0-e6b3-11e7-9930-cafd3fa44599.gif)
![1](https://user-images.githubusercontent.com/16494741/34278673-ff060c50-e6b4-11e7-9006-59542b8c5576.gif)

**Comment by AnotherCommander** [comment]
I cannot reproduce it here (Win10 Home, Imtel HD610 w/ OpenGL 4.4.0 and Win10 Pro with NVidia GTX 750 Ti) and I have a strong suspicion it might be driver related. How old is the gfx driver you are using? Would there be any chance of updating to latest version and testing again?

If that does not work, the only other possibilities I can think of would be:
-  Edit the file <OoliteRoot>/oolite.app/GNUstep/Defaults/.GNUstepDefaults and add the key `use-texture-lod-bias = NO;`, then restart the game.
- Disable any ATI utilities that might be running in the background.

**Comment by Fixer-007** [comment]
>How old is the gfx driver you are using? Would there be any chance of updating to latest version and testing again?

It is latest supported beta version of Catalyst 10.2 driver for Windows Vista, installed on Windows 7 (no driver for 7), it is really old card, my main one had died unfortunately. I have not seen much problems with it in other games.

>Edit the file /oolite.app/GNUstep/Defaults/.GNUstepDefaults and add the key use-texture-lod-bias = NO;, then restart the game.

Does not help

>Disable any ATI utilities that might be running in the background.

Closed CCC, does not help.

**Comment by AnotherCommander** [comment]
> I have not seen much problems with it in other games.

This may or may not be relevant. Are you talking about other OpenGL or DirectX games? Comparisons should be made only against other OpenGL programs.

**Comment by Fixer-007** [comment]
Other OpenGL games.

**Comment by Fixer-007** [comment]
1.84 has the same problem, hmmm, checking more.

**Comment by Fixer-007** [comment]
Looks like older versions are also affected for me, it is probably rare edge case, since videocard is from year ~2005, what can you expect... I will keep it open, maybe someone has the same problem to confirm.

**Comment by AnotherCommander** [comment]
All indications point to faulty or obsolete gfx drivers. This will be closed out in the next few days if no update is received.

**Comment by AnotherCommander** [comment]
Issue closed - almost certainly driver related.
