### ISSUE TITLE
Oolite failed to use default sound device

### ISSUE THREAD

**Issue by GrahamMarlowe** [OoliteProject/oolite#297]
This is a problem, i really want to hear the amazing sounds of Oolite itself.

Sadly when i looked into the Latest.log file it showed that it failed to use the default sound device of Windows 10.

**Comment by AnotherCommander** [comment]
Can you please provide:
- Full system specs.
- Full latest.log after a failed sound initialization.
- Full latest.log after a restart of the game while holding down Shift until the intro screen appears.
- If after a failed sound init there is a file called stderr.txt inside oolite.app, its contents.

Also, please try installing and running the latest available v1.87 nightly build for Windows from [here](https://github.com/OoliteProject/nightlies/releases/tag/1.87.0.180220) Does this work for you?

Finally, amazing sounds? In the default game you mean? Hmmm... ;-)

**Comment by GrahamMarlowe** [comment]
Apparently, i probably (temporarily or permanently) fixed the problem by uninstalling the game and redownload the installer and reinstall the game. Yep, amazing sounds in the default game.

**Comment by AnotherCommander** [comment]
Great to know it has been fixed. Issue closed.
