### ISSUE TITLE
[Linux] Make INSTALL_ROOT_SYSTEMWIDE configurable

### ISSUE THREAD

**Issue by ONL** [OoliteProject/oolite#300]
The install script defines several environment variables, some of which are configurable by the user, like UNATTENDED_INSTALLATION

However, the install script in oolite/installers/posix/setup.body defines INSTALL_ROOT_SYSTEMWIDE="/opt"

It would be nice, if this was customizable, like

if [ ! ${INSTALL_ROOT_SYSTEMWIDE} ]
then
INSTALL_ROOT_SYSTEMWIDE="/opt"
fi

to allow overriding the directory for a system wide installation. This would facilitate packaging the app as a flatpak, because it could directly be installed to /app

**Comment by KonstantinosSykas** [comment]
Hello ONL. 
I am currently working on adding a command-line parameter.

**Example**
`$ oolite-1.86.linux-x86.run --systemwide-path /app`

Would this do the trick for flatpak?

**Comment by KonstantinosSykas** [comment]
Committed e1ffdb6 on that matter.
Checkout tonight's nightly build Linux binary.

**Usage:** `# ./oolite-1.87.0.e1ffdb6.linux-x86_64.run -- --systemwide-directory DIRECTORY`

_Note 1: '#' indicates root shell_
_Note 2: If a preexisting /opt installation exists, it will remain as "orphan", and must be manually deleted, for the time being. Next version of script will try to remove a probable /opt installation too._

**Comment by KonstantinosSykas** [comment]
The flathub opportunity is interesting indeed. However, let's lay low for the time being. I will take it to the boards on the relevant thread you have opened (http://aegidian.org/bb/viewtopic.php?f=9&t=19746).

Concerning the installer enhancement, it was a quick fix, as clean as possible, but there are still some things to consider. I am still working on the following issue that the current fix presents.

How to replicate the issue:
1. Install Oolite systemwide in one directory; e.g. `/opt`
2. Without uninstalling the first installation, proceed in installing Oolite systemwide in another directory; e.g. `/usr/local/games`

at this point you have an orphan installation in `/opt` and all execution shortcuts (i.e. desktop, command line) are linked to the new installation. Let's continue the scenario.

3. Execute `/opt/Oolite/uninstall`. This will uninstall the /opt/Oolite installation but... 😨 
4. Your `/usr/local/games` is now orphan and all execution shortcuts (i.e. desktop, command line) are removed by the uninstall operation performed in Step 3.  🤦‍♂️ 

I am working on handling this by making uninstall aware of an orphan installation.

**Comment by ONL** [comment]
Question is, whether you want to allow arbitrary locations for installation. The "old" method of installing to /opt works fine, except for special use cases like flatpak
Maybe it should be *--flatpak-install* instead of *--systemwide-directory DIRNAME*

Another option would be to place an uninstall-wrapper in /usr/local/bin where the other oolite-wrappers are stored. Then try to invoke the uninstall-wrapper if *--systemwide-directory DIRNAME* is provided during next install, thus cleaning up old installations.

**Comment by KonstantinosSykas** [comment]
Many thanks for the feedback @ONL ! 😎 

Is the `/app` directory created by flatpak? 
The installer assumes an existing system directory is given. 
If the directory is not there then the installation is aborted.

**Comment by ONL** [comment]
Yes, `/app` already exists inside flatpak environments.

**Comment by KonstantinosSykas** [comment]
Orphan installations handled with commit 6174e69.
If no other objections exist, this case will be closed.

**Comment by KonstantinosSykas** [comment]
This is just to summarize the solution given, before closing the case.

The command line parameter `[-- --systemwide-directory DIRECTORY]` is now supported by the installer. This allows systemwide installations to be deployed to a configurable directory. The directory value used for `DIRECTORY` must exist or else the installation will terminate. The `[-- ]` (dash dash space) before the actual parameter is mandatory! The default systemwide installation directory is `/opt`.

**Usage Example**
`# ./oolite-trunk-1.87.0.e1ffdb6.linux-x86_64.run -- --systemwide-directory /usr/local/games`

**Important Note**
The installer will try to uninstall a previous systemwide installation deployed to a different directory. However, only some heuristics are applied on that purpose and not an exhaustive and explicit search.
**It is strongly recommended to uninstall previous installations before proceeding to a new one.**
