### ISSUE TITLE
Caps Lock key affects mouse control

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#306]
It seems that the `Caps Lock` key affects mouse control. I experienced a bunch of weird behaviours when I turned the `Caps Lock` ON in the outside view to rotate the camera and press `1` to go back to the HUD while forgetting the `Caps Lock` ON:

* mouse scroll wheel stopped controlling the throttle setting
* mouse left button would fire only in the forward view, but not in the aft view. Did not test side views as my ship wasn't equipped with them at the time.

**Comment by AnotherCommander** [comment]
Confirmed and good catches. I think I know what's going on. Some more testing and, if all well, will close today.
