### ISSUE TITLE
Fedora 29 and 33 - 1.88/90 fails to run

### ISSUE THREAD

**Issue by brianread108** [OoliteProject/oolite#315]
I get this:

 brianr  ~  GNUstep  Applications  Oolite  ./oolite
./oolite.app/oolite: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory

Erk. It looks like Oolite died with an error. When making an error
report, please copy + paste the log above into the report.

(Press Ctrl-C to continue)

**Comment by AnotherCommander** [comment]
Is the copy of 1.88 downloaded from oolite.org or from the Fedora repository? If it is the latter, can you please download from the website and retry?

**Comment by AnotherCommander** [comment]
Further investigation indicates that libnsl was removed from the Fedora 28 glibc and there are plenty of applications that encountered problems because of this. If installing the game from oolite.org does not help, I would suggest manually installing libnsl from your Fedora repository.

**Comment by brianread108** [comment]
It was installed from oolite.org.

sudo dnf install libnsl 

seems to do the job - many thanks.

**Comment by brianread108** [comment]
Needed the same install for Fedora 33.

**Comment by KonstantinosSykas** [comment]
If I prepare a package for you @brianread108 to test, will you try it?

**Comment by brianread108** [comment]
> The test package can be downloaded at http://terrastorage.no-ip.info/oolite/oolite315-00.tgz .
> It will install an Oolite instance in `~/GNUstep/Applications/Oolite-trunk/` folder.

I get this:
Firefox can't establish a connection to the server at terrastorage.no-ip.info.

**Comment by KonstantinosSykas** [comment]
> 
> I get this:
> Firefox can't establish a connection to the server at terrastorage.no-ip.info.

I've updated some network configuration on this file. Please, try again.

**Comment by brianread108** [comment]
Yes, that install and ran ok.

**Comment by KonstantinosSykas** [comment]
Resolved in 15a7f10
