### ISSUE TITLE
Oolite crashes on Fedora 29 after updating mesa packages to 18.3.3-1

### ISSUE THREAD

**Issue by FrozenSplash** [OoliteProject/oolite#325]
I've just done an update on Fedora 29 and found that Oolite crashes after starting and selecting "Load Commander".

Upon downgrading the "mesa" driver from 18.3.3-1 to 18.2.2-1 Oolite works again.

The failure message was:
    ../src/mesa/main/dlist.c _mesa_delete_list: Assertion `InstSize[opcode] > 0' failed

**Comment by KonstantinosSykas** [comment]
Have you checked with other OpenGL apps? 
Try executing glxgears as a first check.
`$ glxgears`

I quote from Fedora Project
> glxgears (and other OpenGL apps) should run properly and with full acceleration and behave as any other window. Covering them should work properly, they should move smoothly, and should render properly in the overview mode. Overview mode should activate quickly with a smooth transition, and deactivate in the same way. GNOME Shell should run successfully and there should be no glitches or corruption in the display of the desktop or overview mode with GNOME Shell enabled

Considering that nothing has changed for Oolite itself, if you haven't raised this to Fedora project community yet, please, do so. Share the relevant fedora discussion link here, please.

**Comment by FrozenSplash** [comment]
I've tested glxgears with both "mesa" versions 18.3.3-1 and 18.2.2-1 and it runs fine with either, but still Oolite crashes with 18.3.3-1.

**Comment by KonstantinosSykas** [comment]
Could you, please, share the Oolite Latest.log file, following a crash? It should reside under [user home]/.Oolite/Logs/ folder.
Furthermore, please, confirm that you are using the latest Oolite version downloaded from  http://oolite.org/download/

**Comment by FrozenSplash** [comment]
I'm running the latest version 1.88.
Latest Log file attached: [Latest.log](https://github.com/OoliteProject/oolite/files/2897014/Latest.log)

**Comment by brianread108** [comment]
Can confirm I also have the crash on a fully up to date Fedora 29.

**Comment by AnotherCommander** [comment]
@FrozenSplash , @brianread108 Is your Oolite downloaded from oolite.org or from some Fedora repository? This is crucial information.

If you have it downloaded from a repository, please try installing and running the game using the package provided at http://oolite.org/download/,

**Comment by brianread108** [comment]
I am pretty sure it was downloaded from the oolite.org/download and not from a Fedora/Copr repo. I've generally updated it whenver i get an email from your guys for a new version by downloading the "run" executible.

Is there a way to tell absolutely?

**Comment by KonstantinosSykas** [comment]
@FrozenSplash , @brianread108 
To check if you are actually running Oolite using the binaries provided by oolite.org:
1. The desktop icon should have a caption like _Oolite (oolite.org)_ . Try to see (perhaps using an option if the icon is right-clicked), which path is used.
2. If you are using the command line to start Oolite, execute 
`$ which oolite`
This should return the Oolite binary path, if it is a system-wide installation.
3. If you have a home-directory installation, you can ensure you are running Oolite from oolite.org, if you execute 
`$ ~/GNUstep/Applications/Oolite/oolite`

In any case, please, share your installation path.

Mesa crashes due to an assertion committed back in Jan 20, 2018 in the <_mesa_delete_list()> function. 
https://github.com/mesa3d/mesa/commit/6c724fb7c14de3088b51748a781983e76c5d8ee1#diff-29901f943ef8c8345371ec5e906f2160
It seems that it just made its way into Fedora29. 

Please, try _hiding_ the Oolite packaged libSDL by renaming it.
If you have a home-directory installation execute
`$ mv ~/GNUstep/Applications/Oolite/oolite-deps/lib/libSDL-1.2.so.0 ~/GNUstep/Applications/Oolite/oolite-deps/lib/libSDL-1.2.so.0.oolite`

else, if you have a system-wide installation execute
`# mv /opt/Oolite/oolite-deps/lib/libSDL-1.2.so.0 /opt/Oolite/oolite-deps/lib/libSDL-1.2.so.0.oolite`

Now execute Oolite and if it complains that it cannot locate libSDL-1.2.so.0, then, you will have to install libSDL-1.2.so.0 from Fedora repo.

Waiting for your feedback.

**Comment by brianread108** [comment]
I get this:

 ~/GNUstep/Applications/Oolite/oolite
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
oolite: ../src/mesa/main/dlist.c:1205: _mesa_delete_list: Assertion `InstSize[opcode] > 0' failed.
/home/brianr/GNUstep/Applications/Oolite/oolite.app/oolite-wrapper: line 69:  1127 Aborted                 (core dumped) ./oolite.app/oolite "$@"

Erk. It looks like Oolite died with an error. When making an error
report, please copy + paste the log above into the report.

Hiding libSDL.o gives me this:

~/GNUstep/Applications/Oolite/oolite
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
oolite: ../src/mesa/main/dlist.c:1205: _mesa_delete_list: Assertion `InstSize[opcode] > 0' failed.
/home/brianr/GNUstep/Applications/Oolite/oolite.app/oolite-wrapper: line 69:  1499 Aborted                 (core dumped) ./oolite.app/oolite "$@"

Erk. It looks like Oolite died with an error. When making an error
report, please copy + paste the log above into the report.

(Press Ctrl-C to continue)
^C

Loading libSDL from fedora repo:
sudo dnf install libSDL-1.2.so.0
loads "SDL-1.2.15-35.fc29.i686"

Running oolite then gives:

 ~/GNUstep/Applications/Oolite/oolite
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
AL lib: (EE) ALSANoMMapProc: available update failed: Broken pipe
oolite: ../src/mesa/main/dlist.c:1205: _mesa_delete_list: Assertion `InstSize[opcode] > 0' failed.
/home/brianr/GNUstep/Applications/Oolite/oolite.app/oolite-wrapper: line 69:  1657 Aborted                 (core dumped) ./oolite.app/oolite "$@"

Erk. It looks like Oolite died with an error. When making an error
report, please copy + paste the log above into the report.

(Press Ctrl-C to continue)
^C

**Comment by KonstantinosSykas** [comment]
Thank you for testing @brianread108 .
I managed to get my hands on a Fedora29 installation and replicated the issue. It doesn't seem that it is an issue with Oolite libraries. You may revert the Oolite packaged libraries to the previous state. 
I contacted the author of the mesa library in an attempt to understand what is this change about, however, I wouldn't expect a quick fix for that. 
Unless anyone else comes up with a better idea, playing using the previous mesa version seems to be the only workaround for the time being.

**Comment by brianread108** [comment]
ok.
for my my benefit and others, what is the command to revert the version of mesa?

**Comment by KonstantinosSykas** [comment]
Hi @brianread108 ,
I think the following should do the trick:
```$ sudo dnf downgrade mesa-dri-drivers```

Here is what I did to the testbed environment.
```
[liveuser@dhcp-9-233-89-52 Downloads]$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 18.2.2
[liveuser@dhcp-9-233-89-52 Downloads]$ sudo dnf update mesa-dri-drivers.x86_64
Last metadata expiration check: 1:58:43 ago on Mon 25 Feb 2019 06:04:31 AM EST.
Dependencies resolved.
===============================================================================================================================
 Package                            Arch                     Version                           Repository                 Size
===============================================================================================================================
Upgrading:
 mesa-dri-drivers                   x86_64                   18.3.4-1.fc29                     updates                    15 M
 mesa-filesystem                    x86_64                   18.3.4-1.fc29                     updates                    17 k

Transaction Summary
===============================================================================================================================
Upgrade  2 Packages
...[rest of installation output is truncated]
[liveuser@dhcp-9-233-89-52 Downloads]$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 18.3.4
[liveuser@dhcp-9-233-89-52 Downloads]$ sudo dnf downgrade mesa-dri-drivers
Last metadata expiration check: 2:06:43 ago on Mon 25 Feb 2019 06:04:31 AM EST.
Dependencies resolved.
===============================================================================================================================
 Package                            Arch                     Version                            Repository                Size
===============================================================================================================================
Downgrading:
 mesa-dri-drivers                   x86_64                   18.2.2-1.fc29                      fedora                    13 M
 mesa-filesystem                    x86_64                   18.2.2-1.fc29                      fedora                    18 k

Transaction Summary
===============================================================================================================================
Downgrade  2 Packages
...[rest of installation output is truncated]
[liveuser@dhcp-9-233-89-52 Downloads]$ glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 18.2.2
[liveuser@dhcp-9-233-89-52 Downloads]$ 
```

**Comment by brianread108** [comment]
Can confirm that worked fine.  Good luck finding the problem!

**Comment by brianpaul** [comment]
I've found/fixed the Mesa bug.  I'm surprised it wasn't found sooner.  I'll have the patch reviewed and committed soon.

**Comment by brianpaul** [comment]
The reason this wasn't found before is oolite is doing something unusual.  It basically calls:
list = glNewList(1);
glDeleteLists(list, 1);
before any other display list commands.  If you want to know more details, look for the upcoming git commit/fix.

**Comment by KonstantinosSykas** [comment]
@brianpaul thank you for your feedback.

The reason of the bug not found sooner, I think it's because mesa versions > 18.2.2 (i.e. last known version w/o the bug) have just started making their way into linux distros. 

Concerning the upcoming mesa git commit/fix, I hope it will be coming soon, to make it as soon as possible into the linux distros. 
I could perhaps give it a try on a Fedora29 (just set it up to replicate this issue) when it's made available in GitLab.

**Comment by brianpaul** [comment]
On Tue, Feb 26, 2019 at 3:36 AM Konstantinos Sykas <notifications@github.com>
wrote:

> @brianpaul <https://github.com/brianpaul> thank you for your feedback.
>
> The reason of the bug not found sooner, I think it's because mesa versions
> > 18.2.2 (i.e. last known version w/o the bug) have just started making
> their way into linux distros.
>
> Concerning the upcoming mesa git commit/fix, I hope it will be coming
> soon, to make it as soon as possible into the linux distros.
> I could perhaps give it a try on a Fedora29 (just set it up to replicate
> this issue) when it's made available in GitLab.
>
>
I pushed the fix to the Mesa repo this morning.  I think it'll be a month
or so before an official Mesa release contains the fix.  Then it's up to
each distro to incorporate the new Mesa release when it suites them.

-Brian

**Comment by KonstantinosSykas** [comment]
The fix committed by @brianpaul has been tested on Fedora 29. I confirm that it resolves the case. 
A workaround till the fix reaches the Linux distros is to keep mesa at version18.2.2. 

@FrozenSplash & @brianread108 
Thank you both for reporting and testing.

This case will now be closed.

**Comment by AnotherCommander** [comment]
Many thanks also to @brianpaul for the quick response and fix to the Mesa drivers. Glad to be able to declare this closed.
