### ISSUE TITLE
Index out of range error on F5 Status screen

### ISSUE THREAD

**Issue by phkb** [OoliteProject/oolite#333]
(These instructions are for a Windows environment - not sure about Linux or Mac)

On F5 Status screen, when viewing a page that has both the "MORE" and "BACK" lines shown. Select the "BACK" line by pressing the Up Arrow key. Then use Alt-TAB to switch to another app. Use Alt-TAB again to switch back to Oolite. The "MORE" line will now be selected. Then press the Down Arrow key. The following error will be displayed multiple times:

> 09:13:43.497 [exception]: ***** Exception in pollDockedControls [GUI keys]: NSRangeException : Index 30 is out of range 30 (in 'objectAtIndex:')

**Comment by phkb** [comment]
Occurs in full screen and windowed modes.

**Comment by AnotherCommander** [comment]
Can reproduce up to the point where More is selected when coming back to the F5 screen. I can't get the exception. to fire. Can you please provide the full list of equipment OXPs you use in your case and maybe a screenshot of the F5 screens listing everything? I'll try to reconstruct it exactly, but for now I can't get the error to trigger.

**Comment by phkb** [comment]
Just did a quick recheck - it doesn't happen with the standard HUD, which only has 8 lines of data on the F5 screen. I'm using Xenon HUD, which has allow_big_gui set to true and 13 lines of data.

Hopefully that's the key bit of info, but I'll start work on some screenshots and OXP listing in the meantime.

**Comment by phkb** [comment]
<a href="https://postimg.cc/vg8BZGxW" target="_blank"><img src="https://i.postimg.cc/vg8BZGxW/oolite-346.png" alt="oolite-346"/></a><a href="https://postimg.cc/Hr5jSZC7" target="_blank"><img src="https://i.postimg.cc/Hr5jSZC7/oolite-345.png" alt="oolite-345"/></a><a href="https://postimg.cc/2qDygQz9" target="_blank"><img src="https://i.postimg.cc/2qDygQz9/oolite-347.png" alt="oolite-347"/></a>
Screenshots

**Comment by phkb** [comment]
Link to Latest.log zip file with list of OXP's: [Latest.log.zip](https://app.box.com/s/l5yb2fcdp23nuz1ehjorqtkbhj4krsvy)

**Comment by AnotherCommander** [comment]
I have replicated it. You don't even need to Alt-Tab out of the game. Just pressing down arrow when highlighting More or up arrow when highlighting Back is enough to trigger the exception.

**Comment by AnotherCommander** [comment]
I think it's fixed. Please test latest commit and let me know.

**Comment by phkb** [comment]
Yep, issue is resolved! Thanks!
