### ISSUE TITLE
screenshot permissions for Wikimedia

### ISSUE THREAD

**Issue by gilbertohasnofb** [OoliteProject/oolite#343]
A couple of months ago I edited Oolite's wikipedia page (https://en.wikipedia.org/wiki/Oolite_(video_game)) and added several new screenshots. Yesterday I have been contacted by Wikimedia (who hosts all Wikipedia images) in relation to the permission of the screenshots. Apparently, they started being very strict with screenshots of software recently; instead of understanding that a screenshot is the creation of the user, or even that it is a fair usage of a software, they are interpreting that a screenshot is part of the program and thus carries the same license. I myself disagree wholeheartedly with such interpretation, but that's not up to me.

Given that Oolite is licensed with both GPLv2 and CC-BY-NC-SA, there is a conflict since they can't have images licensed under a -NC restriction. So there are two options right now: 1) remove all screenshots of Oolite's wikipedia page or 2) authorize the use of those images as CC-BY-SA only (without -NC). 

Here is the full conversation I had by email:

> Dear Gilberto Agostinho,
> 
> Thank you for your permission to use the image(s). Oolite software is licensed under  Creative Commons CC-BY-NC-SA.
> 
> Please note that the license components -nc- (noncommercial) and -nd- (no derivatives) are not usable for Wikimedia Commons. For the reasons please see <https://commons.wikimedia.org/wiki/Commons:Licensing/Justifications>.
> 
> If the creator agrees to publish the image(s) under a license compatible with Commons, please advise.
> 
> Yours sincerely,
> Valeria Domínguez

> Dear Valeria Dominguez,
>
> I am not the software owner but the image creator, which I am happy to 
> license under any CC license which might be suitable. I understand that 
> Oolite itself might not be licensed with the required permissions, but I 
> am not distributing the software itself, just an image. Otherwise no 
> screenshots of any proprietary software would be permissible, right?
>
> Best wishes,
> Gilberto

> Dear Gilberto Agostinho,
> 
> Good, you made a screenshot of a software. That it's a derivative works, and remains the original license. If the creator agrees to publish the image(s) under a license compatible with Commons, please advise.
> 
> Yours sincerely,
> Valeria Domínguez

**Comment by cim--** [comment]
> Given that Oolite is licensed with both GPLv2 and CC-BY-NC-SA, there is a conflict since they can't have images licensed under a -NC restriction.

The dual licensing means that derivative works can be used under *either* license. It's impossible to follow all the terms of both licenses at once, so derivative works can either
 - pick GPLv2 only
 - pick CC-BY-NC-SA only
 - also dual license, allowing future re-users to also use it under either terms, but not both at once.

Commons calls this multi-licensing at https://commons.wikimedia.org/wiki/Special:MyLanguage/Commons:Licensing#Multi-licensing so they should be fine with that.

Your screenshots can therefore be licensed under GPLv2, if you want, which appears to be an acceptable license for Commons. Obviously it's up to you whether you're happy with the specific terms of GPLv2 for your pictures.

(Note: screenshots containing OXPs must, presumably, under this policy, be licensed on a license compatible with all featured OXPs, so any OXPs you take pictures of must also have a GPLv2 licensing option, and most of them don't)

**Comment by gilbertohasnofb** [comment]
@cim-- Thanks, cim!

After much back and forth, the solution they accepted was to change the screenshots to a compatible license (I chose CC-0) and consider the software as GPLv2. I find this whole affair quite annoying and the people behind it overzealous, as I feel that screenshots clearly fall into fair use. It's ludicrous to expect an image to carry the same license as the software itself when the software is obviously not being distributed through the image.

Concerning the OXP, I frankly don't want to open that can of worms. It's just a screenshot to illustrate the wikipedia article and, hopefully, attract new players. CC-0 will suffice for me.
