### ISSUE TITLE
Expansion pack filters should not heed initial space

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [OoliteProject/oolite#376]
In Oolite 1.9 (and I imagine in previous versions), typing `k: harder` does not match 'harder'. This heeding of the initial space really threw me - I thought I must have botched the upload of my OXZ - and so I submit it should be changed. Thanks.

**Comment by oocube** [comment]
Does this still occur on Oolite 1.90? And the latest 1.91 build?
