### ISSUE TITLE
Official Raspberry Pi build? (ARM64 or ARM32 Linux)

### ISSUE THREAD

**Issue by ghost** [OoliteProject/oolite#386]
### Official Raspberry Pi build? 
(Or ARM64 Linux build that works on Raspberry Pi)

So, one day around a year ago I found oolite. I fell in **love** with it because well space games are _awesome_ **AND** it was open source. I really loved it and played it on **Raspberry Pi**, it was in the package manager. A few months ago it simply **_disappeared_** from the package manager 😭 and off my machine when I tried `sudo apt update && sudo apt upgrade`. Is it possible to have an official Raspberry Pi build of oolite? I haven't tried building it myself in a while so I'll try that out later today if I have some time. o7 CMDRS

Edit:
    In case you don't know o7 is a salute 🖖

**Comment by KonstantinosSykas** [comment]
Does this help?!?
https://archive.raspbian.org/raspbian/pool/main/o/oolite/

**Comment by CMDR-Piboy314** [comment]
That helps, although it was last updated in 2016...

**Comment by CMDR-Piboy314** [comment]
Sorry, my account was deleted because I am underage to use this site.

**Comment by HiranChaudhuri** [comment]
While we are reviving the CI/CD pipeline, we use the Github hosted runners. ARM64 is none of the offered platforms there.
https://github.com/HiranChaudhuri/OoliteBuilder/blob/main/files/buildAppDir.sh#L21

With that I doubt there will be a new Rasbian release anytime soon.
Would you like to provide a self-hosted runner? That could do the trick.
