### ISSUE TITLE
TAF Left Arrow Does Not Work (new_keyconfig branch)

### ISSUE THREAD

**Issue by AnotherCommander** [OoliteProject/oolite#389]
In the new_keyconfig branch, the left arrow to reduce TAF does not currently work. The error is here:

https://github.com/OoliteProject/oolite/blob/4e5dd1b4347838fe5756db74fa474c7a6bb098a4/src/Core/Entities/PlayerEntityControls.m#L2049

This line should read
`float newTimeAccelerationFactor = [self checkKeyPress:n_key_gui_arrow_left] ?`

**Comment by phkb** [comment]
Thanks! There's another one similar to that one actually, down around line 4923.

**Comment by phkb** [comment]
Latest push should fix both those items.

**Comment by AnotherCommander** [comment]
Indeed it does, closing this one.
