### ISSUE TITLE
Clarification of License

### ISSUE THREAD

**Issue by natewrench** [OoliteProject/oolite#401]
Is it GPLv2 or any later version or just GPLv2 only?

**Comment by AnotherCommander** [comment]
Disclaimer: I am not a legal expert and welcome corrections in case I am mistaken, but I will try to provide my interpretation on the license status based on the information included both in the LICENSE.TXT document distributed with the source code and the official text of GPL v2 (GPL.TXT in the source distribution).

So, Oolite has a license for its binaries and a license for its assets. Let's examine them one by one.

Regarding binaries, LICENSE.TXT states:
```
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
```
The GPL v2 license text, under paragraph 9 states the following:
```
If the Program specifies a version number of this License which 
applies to it and "any later version", you have the option of 
following the terms and conditions either of that version or of any 
later version published by the FreeSoftware Foundation.
```
Therefore, based on the above, binaries are distributed under _either_ GPL v2, _or_ any later GPL version, at your own discretion.

Regarding assets, LICENSE.TXT states:
```
Additionally, all artwork – 3D models, images and sounds – included in
the work, as well as configuration files, are also licensed under the
Creative Commons Attribution-NonCommercial-ShareAlike License version
3.0. This means that these files may be distributed under either license
at your discretion.
```
According to this, assets are distributed under _either_ GPL v[whatever you have decided the binaries will be distributed under] _or_ CC BY-NC-SA 3.0, again at your own discretion.

I hope this answers your question.
