### ISSUE TITLE
sor4y

### ISSUE THREAD

**Issue by samelimbo** [OoliteProject/oolite#415]
sorry about this site for this issue.
i cannot log into oolite bullitin board.
forgot password link sends no email
that includes creating a new account.
cannot find 'contact us' link
username: limbo
new username: samelimbo
any help would be appreciated.
thankyou in advance

**Comment by AnotherCommander** [comment]
Closing since limbo's access to the forum has been re-established.

**Comment by samelimbo** [comment]
many thanks for aĺlowing me to do that


-------- Original message --------
From: AnotherCommander ***@***.***>
Date: 12/12/22 17:02 (GMT+10:00)
To: OoliteProject/oolite ***@***.***>
Cc: samelimbo ***@***.***>, Author ***@***.***>
Subject: Re: [OoliteProject/oolite] sor4y (Issue #415)


Closing since limbo's access to the forum has been re-established.
