### ISSUE TITLE
Forum is down - how to recover?

### ISSUE THREAD

**Issue by HiranChaudhuri** [OoliteProject/oolite#475]
The forum went down, and the message displayed on http://aegidian.org/bb/ does not really look encouraging.
Either this gets recovered or we need to activate alternatives.

I want to point out that there is a number of alternatives - we probably need to point the community somewhere via the web page, wiki and other links.

**Comment by stimer** [comment]
DON'T PANIC )

**Comment by AnotherCommander** [comment]
Are we good to close this? Forum is now on bb.oolite.space and working.
