### ISSUE TITLE
Duplicate reports on station entry.

### ISSUE THREAD

**Issue by StickyDigit** [OoliteProject/oolite#478]
In 1.90 and 1.91.0.7595-240312-1dd89be I often see double reporting of capture escape pod or delivery reports. See image below.

![DoubleData](https://github.com/OoliteProject/oolite/assets/30390101/544e2c0e-0863-408e-97e2-904ee53e31f6)

**Comment by AnotherCommander** [comment]
Pretty certain this is an OXP bug. The duplicated message in the sample screen is not part of the core game.

**Comment by StickyDigit** [comment]
You're probably right. I'll re-open this if I see it only on escape capsules or similar.
