### ISSUE TITLE
Unable to save keyboard config

### ISSUE THREAD

**Issue by StickyDigit** [OoliteProject/oolite#479]
I'm trying to use the keyboard config screen to add keys for an OXP primeable (waypoint here).

For example, I can set the '#' key for activate, but selecting save does nothing. On my UK laptop keyboard, # is a base key, and ~ is shifted #.

I have tried different keys and primeables.

Latest.log gets this, five times per attempt.

`[exception]: ***** Exception checking controls [pollDemoControls]: NSInvalidArgumentException : Can not determine type information for -[GSDictionary setObject:forKey:]`

1.91.0.7599-240321-7953d4a-linux-dev-x86_64

**Comment by phkb** [comment]
I can confirm this error on Linux. Doesn't occur on the Windows build. Investigating now and will report back.

**Comment by phkb** [comment]
@StickyDigit if you're able to test PR #481 and confirm it works, I'll push it into master.

**Comment by StickyDigit** [comment]
That's working for me.

Oooh! I like the new coloured section headers in the key config screens.

**Comment by AnotherCommander** [comment]
OK to close this?

**Comment by StickyDigit** [comment]
Yes. It's working well.
Thanks.
