### ISSUE TITLE
Formating of help popup window on Windows has issues

### ISSUE THREAD

**Issue by phkb** [OoliteProject/oolite#483]
On Windows 11 (23H2)
[![image.png](https://i.postimg.cc/fLzNS2fr/image.png)](https://postimg.cc/p967gB7f)

**Comment by brianread108** [comment]
and on Linux:
![Screenshot from 2024-05-25 06-33-47](https://github.com/OoliteProject/oolite/assets/9008937/c3f1e24c-e6f4-484d-a069-d75c5c458bc2)

**Comment by AnotherCommander** [comment]
@phkb  What desktop resolution and DPI scaling are you running? If you remove one \t from each line of text in main.m, does this fix it for you? I can confirm that if I do this, it still can display fine on my system and should, theoretically, fix your formatting too.

@brianread108 The Windows message box fonts are typcially variable-width, while the Linux console fonts are typically monospaced. As mentioned in the pull request for this feature, text formatting was optimized for the Windows message box (and apparently, I still failed on that!). Sort of having two different blocks of pretty much the same help text (one for each OS, not too fond of the idea) plus or minus a few tab characters, the Linux text formatting is expected to be slightly different.

**Comment by AnotherCommander** [comment]
It looks like this for me with one tab less on each line. I am on Windows 11 23H2 (10.0.22631.3593) , 1920x1080, 125% scaling:

![WindowsHelpWindow01](https://github.com/OoliteProject/oolite/assets/623526/f3e09f23-03bc-427f-894e-cca828b0f410)

@phkb I believe it should lpok the same for you too,

**Comment by phkb** [comment]
Mine was at 100% scaling. Just recompiling with the tweak now.

**Comment by phkb** [comment]
OK, after removing a "\t" from every line, I get this:
[![image.png](https://i.postimg.cc/JnWHSkWL/image.png)](https://postimg.cc/Z9Vqd0R7)

**Comment by AnotherCommander** [comment]
OK, so the culrpit is indeed DPI scaling. Looking into it now, but chances are that we may have to adjust the text for 100% and live with it for the rest of the scaling options.

**Comment by AnotherCommander** [comment]
@phkb Please test commit 0b5b52b. On my system it works correctly with all available Windows scaling factors.

**Comment by phkb** [comment]
Looking excellent at 100% scaling:
[![image.png](https://i.postimg.cc/TPn22hX9/image.png)](https://postimg.cc/GBhnqLt8)

**Comment by phkb** [comment]
I think this is resolved now.

**Comment by brianread108** [comment]
Linux  - Better:
![Screenshot from 2024-05-26 20-02-01](https://github.com/OoliteProject/oolite/assets/9008937/5059a8f8-0894-4abd-ab33-6dd612896721)
