### ISSUE TITLE
Please assign Ctrl-n and Ctrl-b to the equipments

### ISSUE THREAD

**Issue by Norbylite** [OoliteProject/oolite#49]
When I asked for more equipment keys in the forum cim said too few left, but I think Ctrl-keys are less valuable and many OXP can benefit from the more input buttons. 

I would like to ask a decision from the developers: may Ctrl-n and Ctrl-b keys are allocated for the equipments or not?

**Comment by HiranChaudhuri** [comment]
A lot of time passed. Does this cover the problem?
http://aegidian.org/bb/viewtopic.php?p=285622#p285622

**Comment by phkb** [comment]
Well, this does: #476
