### ISSUE TITLE
Windows:Splash Screen & Vertical Refresh = on : Crash

### ISSUE THREAD

**Issue by JensAyton** [OoliteProject/oolite#6]
[Berlios bug #18921](https://developer.berlios.de/bugs/?func=detailbug&bug_id=18921&group_id=3577)
(Category: Game Engine, Priority: 5)

Submitted by: frame

Windows 7 Up to date.

Oolite 1.76 & Oolite 1.77 & Oolite 1.77-test

On AMD Radeon 12.9 drives with two HD6670 GFX cards, while setting vertical refresh to any setting that will set vertical refresh to ON & having the splash screen at its default setting which is on.

Will cause Oolite not to start up.

Allways off = OK
Allways off unless application specifies = OK
Allways on unless application specifies = Crash
Allways on = Crash.
***
Comment by: @AnotherCommander 

Apparently this is extremely difficult to reproduce without the right card/drivers combination. Is there any chance of providing us with a debug backtrace (requires building debug version of Oolite from source)?
***
Comment by: frame

Yrol Denjah running windows XP 32 bit & had a poor FPS. We fixed it via IRC. The splash screen was the culprit of his Poor FPS. He was using a ATI/AMD card. 

wyvern_mommy have the same problem and have disabled splash screen & she is using Vista SP3 32 bit 

So I would claim (without being to clever about it) it is not directly a drivers/GFX card combo problem, by that of the very few people that are on IRC. Two already have had problems with the splash screen. 

My windows version is 64 bit. so it spans across bit versions too. 

My logic tells me something with the splash screen is fundamentally wrong, when 3 different windows versions have issues with it. 
***
Comment by: frame

regarding the debug backtrace. nope. not at the present time.
***
Comment by: @AnotherCommander 

@Kaks commited some adjustments to the splash screen code on r5672. Can you re-test with any nightly newer than that revision and let us know whether it works or not? Thanks in advance.
***
Comment by: frame

Did not help I'm afraid. Same Behaviour with the vertical refresh = on in any case. 

I'll try to get the debug trace installed when I get the time.

**Comment by AnotherCommander** [comment]
Not reproducible on a wide variety of Windows PCs with current version (1.82). Closing.
