### ISSUE TITLE
Possible bug after docking

### ISSUE THREAD

**Issue by JensAyton** [OoliteProject/oolite#86]
Bug report from email:

> I’ve been playing Oolite for a couple of years now. Recently I’ve noticed some odd behaviour a couple of times but only
> now recognised the common theme.
> I’ve upgraded by ship to a Boa Class Cruiser with a docking computer.
> I entered a docking station with a load of cargo, mostly stuff you would sell at an industrial planet (food, radio actives, wines etc).
> Normally when I approach a space station I use the keyboard short cut shift+C to get in quickly. On this occasion I just used
> C and allowed the docking computer to run its own course. When I got in I tried to sell my cargo.
> When I selected an item and used to the arrow keys to sell an item it zeroised the item count but only credited me with the cost of 1 ton.
> This doesn’t happen if I dock with shift+C.
>
> Hope this makes sense.

**Comment by AnotherCommander** [comment]
No further information provided. We cannot reproduce; issue closed.
